from __future__ import annotations

VERIFIED_SEED_ROWS = [
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2024-01-22",
        "closing_date": "2024-02-06",
        "title": "Medical Reagent Kits, Lab Reagent / Chemicals & Misc. Items",
        "description": "Procurement of medical reagent kits, laboratory reagents and chemicals, and miscellaneous medical items for a Pakistan Navy hospital laboratory requirement.",
        "buyer": "Pakistan Navy",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Pakistan Navy",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "15 days",
        "item_no": "1",
        "item_description": "Medical reagent kits, lab reagents / chemicals and miscellaneous medical items",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000001234E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000001234E",
        "query_text": "medical reagent kits, lab reagents, chemicals, Pakistan Navy, medical, healthcare, laboratory",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2024-10-03",
        "closing_date": "2024-10-22",
        "title": "Proc of Electro Medical Equipment (05 L/Item)",
        "description": "Procurement of electro medical equipment including fetal monitor, operating lights, incubator, color doppler ultrasound, and ECG machines for PAC Hospital Kamra.",
        "buyer": "PAC Hospital Kamra",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "PAC Hospital Kamra",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "120 days",
        "item_no": "1",
        "item_description": "Electro medical equipment including fetal monitor, operating lights, incubator, color doppler ultrasound, and ECG machines",
        "item_uom": "5 lots",
        "item_quantity": "5",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000002479E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000002479E",
        "query_text": "electro medical equipment, fetal monitor, incubator, ultrasound, ECG, hospital, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Fetal monitor", "item_quantity": "1", "item_uom": "lot"},
            {"item_no": "2", "item_description": "Operating lights", "item_quantity": "1", "item_uom": "lot"},
            {"item_no": "3", "item_description": "Incubator", "item_quantity": "1", "item_uom": "lot"},
            {"item_no": "4", "item_description": "Color doppler ultrasound", "item_quantity": "1", "item_uom": "lot"},
            {"item_no": "5", "item_description": "ECG machines", "item_quantity": "1", "item_uom": "lot"},
        ],
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-03-28",
        "closing_date": "2026-04-27",
        "title": "Daily LP Contract Of (Medicines/Disposables/ Lab Kits/ Implants) FY 2026-27",
        "description": "Daily LP contract for medicines, disposables, lab kits and implants for Combined Military Hospital Malir Cantt Karachi for FY 2026-27.",
        "buyer": "Combined Military Hospital Malir Cantt Karachi",
        "classification": "healthcare tender notice",
        "status": "published",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Combined Military Hospital Malir Cantt Karachi",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "365 days",
        "item_no": "1",
        "item_description": "Medicines, disposables, lab kits and implants for FY 2026-27",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000003271E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000003271E",
        "query_text": "medicines, disposables, lab kits, implants, CMH Malir Cantt Karachi, hospital, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Medicines", "item_quantity": "1", "item_uom": "category"},
            {"item_no": "2", "item_description": "Disposables", "item_quantity": "1", "item_uom": "category"},
            {"item_no": "3", "item_description": "Lab kits", "item_quantity": "1", "item_uom": "category"},
            {"item_no": "4", "item_description": "Implants", "item_quantity": "1", "item_uom": "category"},
        ],
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-04-29",
        "closing_date": "2026-05-18",
        "title": "Bulk Purchase of PVMS, NIV, NIF Medicines, NIV Lab Kits, X-Ray films, Disposable Surgical Items, Ortho Implants, IOL Kits, Anti Cancer Medicines and PVMS Dental Items for Financial year 2026-27 (1st July 2026 to 30 Jun 2027) CMH Pano Aqil",
        "description": "Bulk purchase of medicines, lab kits, X-ray films, disposable surgical items, ortho implants, IOL kits, anti-cancer medicines, and dental items for CMH Pano Aqil for FY 2026-27.",
        "buyer": "Combined Military Hospital Pano Aqil",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Combined Military Hospital Pano Aqil",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "365 days",
        "item_no": "1",
        "item_description": "Medicines, lab kits, X-ray films, disposable surgical items, ortho implants, IOL kits, anti-cancer medicines, and dental items",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000005222E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000005222E",
        "query_text": "medicines, lab kits, x-ray films, surgical disposables, ortho implants, anti cancer medicines, dental items, CMH Pano Aqil, hospital, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Medicines", "item_quantity": "1", "item_uom": "category"},
            {"item_no": "2", "item_description": "Lab kits", "item_quantity": "1", "item_uom": "category"},
            {"item_no": "3", "item_description": "X-ray films", "item_quantity": "1", "item_uom": "category"},
            {"item_no": "4", "item_description": "Disposable surgical items", "item_quantity": "1", "item_uom": "category"},
            {"item_no": "5", "item_description": "Ortho implants", "item_quantity": "1", "item_uom": "category"},
            {"item_no": "6", "item_description": "IOL kits", "item_quantity": "1", "item_uom": "category"},
            {"item_no": "7", "item_description": "Anti-cancer medicines", "item_quantity": "1", "item_uom": "category"},
            {"item_no": "8", "item_description": "Dental items", "item_quantity": "1", "item_uom": "category"},
        ],
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-03-13",
        "closing_date": "2026-04-03",
        "title": "Pharmacy / Medical Store, NIF, NIV And Disposables for Operation Theatre",
        "description": "Daily LP contract of medicine, disposables and lab kits items for Combined Military Hospital Multan for FY 2026-27.",
        "buyer": "Combined Military Hospital (CMH) Multan",
        "classification": "healthcare tender notice",
        "status": "published",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Combined Military Hospital (CMH) Multan",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "365 days",
        "item_no": "1",
        "item_description": "Medicines, disposables and lab kits items for FY 2026-27",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000002406E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000002406E",
        "query_text": "medicines, disposables, lab kits, CMH Multan, hospital, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Medicines", "item_quantity": "1", "item_uom": "category"},
            {"item_no": "2", "item_description": "Disposables", "item_quantity": "1", "item_uom": "category"},
            {"item_no": "3", "item_description": "Lab kits", "item_quantity": "1", "item_uom": "category"},
        ],
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-03-18",
        "closing_date": "2026-04-08",
        "title": "Daily LP of Medicine/Disposable and Lab Kits Items - FY 2026/27",
        "description": "Daily LP of medicine, disposable and lab kits items for Army Cardiac Hospital Lahore for FY 2026-27.",
        "buyer": "Army Cardiac Hospital Lahore",
        "classification": "healthcare tender notice",
        "status": "published",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Army Cardiac Hospital Lahore",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "30 days",
        "item_no": "1",
        "item_description": "Medicine, disposable and lab kits items for FY 2026-27",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000002427E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000002427E",
        "query_text": "medicine, disposable, lab kits, Army Cardiac Hospital Lahore, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Medicine", "item_quantity": "1", "item_uom": "category"},
            {"item_no": "2", "item_description": "Disposable items", "item_quantity": "1", "item_uom": "category"},
            {"item_no": "3", "item_description": "Lab kits", "item_quantity": "1", "item_uom": "category"},
        ],
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-04-29",
        "closing_date": "2026-05-14",
        "title": "Daily LP Contract, FY 26-27",
        "description": "Publication of advertisement for daily LP contract of medical stores including medicines, disposables, lab kits and implants for CMH Sialkot for FY 2026-27.",
        "buyer": "Medical Store, Combined Military Hospital (CMH) Sialkot",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Combined Military Hospital Sialkot",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "365 days",
        "item_no": "1",
        "item_description": "Medicines, disposables, lab kits and implants for FY 2026-27",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000005205E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000005205E",
        "query_text": "medical stores, medicines, disposables, lab kits, implants, CMH Sialkot, hospital, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Medicines", "item_quantity": "1", "item_uom": "category"},
            {"item_no": "2", "item_description": "Disposables", "item_quantity": "1", "item_uom": "category"},
            {"item_no": "3", "item_description": "Lab kits", "item_quantity": "1", "item_uom": "category"},
            {"item_no": "4", "item_description": "Implants", "item_quantity": "1", "item_uom": "category"},
        ],
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-03-10",
        "closing_date": "2026-03-25",
        "title": "CMH Nowshera/ Cherat Daily LP Contract Medicine/Disposable/Lab Kits/Implants FY-2026/27",
        "description": "Daily local purchase contract for medicines, disposables, lab kits and implants for CMH Nowshera / Cherat for FY 2026-27.",
        "buyer": "Combined Military Hospital Nowshera / Cherat",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Combined Military Hospital Nowshera / Cherat",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "365 days",
        "item_no": "1",
        "item_description": "Medicines, disposables, lab kits and implants for FY 2026-27",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000002225E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000002225E",
        "query_text": "medicines, disposables, lab kits, implants, CMH Nowshera, Cherat, hospital, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Medicines", "item_quantity": "1", "item_uom": "category"},
            {"item_no": "2", "item_description": "Disposables", "item_quantity": "1", "item_uom": "category"},
            {"item_no": "3", "item_description": "Lab kits", "item_quantity": "1", "item_uom": "category"},
            {"item_no": "4", "item_description": "Implants", "item_quantity": "1", "item_uom": "category"},
        ],
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-04-20",
        "closing_date": "2026-05-05",
        "title": "Purchase of Electro-Medical Equipment for Surgery Department under PSDP project for financial year 2025-26 & 2026-27",
        "description": "Purchase of electro-medical equipment for the Surgery Department of Federal Government Polyclinic under PSDP for FY 2025-26 and 2026-27.",
        "buyer": "Federal Government Polyclinic (PGMI)",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Federal Government Polyclinic (PGMI)",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "120 days",
        "item_no": "1",
        "item_description": "Electro-medical equipment for Surgery Department",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000004606E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004606E",
        "query_text": "electro-medical equipment, surgery department, polyclinic, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "3D Laparoscopic Unit with basic set", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "2", "item_description": "4K Laparoscopy Camera Complete Tower", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "3", "item_description": "Blood Warmer", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "4", "item_description": "Cautery Unit", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "5", "item_description": "Choledochoscope", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "6", "item_description": "Dermatome with accessories", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "7", "item_description": "Flexible Sigmoidoscope", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "8", "item_description": "Laparoscopic Bariatric Set", "item_quantity": "1", "item_uom": "set"},
            {"item_no": "9", "item_description": "Laparoscopic Stapling Gun", "item_quantity": "8", "item_uom": "units"},
            {"item_no": "10", "item_description": "Laser Machine with accessories", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "11", "item_description": "Ligasure Hand Pieces", "item_quantity": "50", "item_uom": "pieces"},
            {"item_no": "12", "item_description": "Ligasure Hand Pieces Open", "item_quantity": "50", "item_uom": "pieces"},
            {"item_no": "13", "item_description": "Nerve Stimulator", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "14", "item_description": "Open Stapling Gun", "item_quantity": "30", "item_uom": "units"},
            {"item_no": "15", "item_description": "Portable Ultrasound", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "16", "item_description": "Sterilization Solution Sprayer", "item_quantity": "4", "item_uom": "units"},
            {"item_no": "17", "item_description": "Heavy Duty Suction Machine", "item_quantity": "4", "item_uom": "units"},
            {"item_no": "18", "item_description": "Thomas Splint Adult Young Large Size", "item_quantity": "10", "item_uom": "units"},
            {"item_no": "19", "item_description": "Vascular Clamp Set", "item_quantity": "2", "item_uom": "sets"},
            {"item_no": "20", "item_description": "Vessel Sealer Generator", "item_quantity": "1", "item_uom": "unit"},
        ],
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-04-20",
        "closing_date": "2026-05-05",
        "title": "Purchase of Electro-Medical Equipment for Cardiology Department under PSDP project for financial year 2025-26 & 2026-27",
        "description": "Purchase of electro-medical equipment for the Cardiology Department of Federal Government Polyclinic under PSDP for FY 2025-26 and 2026-27.",
        "buyer": "Federal Government Polyclinic (PGMI)",
        "classification": "healthcare tender notice",
        "status": "cancelled",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Federal Government Polyclinic (PGMI)",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "120 days",
        "item_no": "1",
        "item_description": "Electro-medical equipment for Cardiology Department",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000004646E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004646E",
        "query_text": "electro-medical equipment, cardiology department, polyclinic, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Provision / Installation of Cath Lab Machine", "item_quantity": "1", "item_uom": "lot"},
            {"item_no": "2", "item_description": "Electro hydraulic moveable Beds", "item_quantity": "30", "item_uom": "beds"},
            {"item_no": "3", "item_description": "ECG Machine", "item_quantity": "16", "item_uom": "units"},
            {"item_no": "4", "item_description": "Defibrillator", "item_quantity": "9", "item_uom": "units"},
            {"item_no": "5", "item_description": "Angiography Complete system with complete accessories", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "6", "item_description": "Automatic CPR Machine with Defibrillator", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "7", "item_description": "ECHO-Cardiography", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "8", "item_description": "Portable ECHOCardiography", "item_quantity": "1", "item_uom": "unit"},
        ],
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-05-13",
        "closing_date": "2026-06-05",
        "title": "Procurement of MR-LINAC under JPMC's GDP / Grant for Financial Year 2025-26",
        "description": "Procurement of MR-LINAC for JPMC under grant funding for FY 2025-26.",
        "buyer": "JPMC",
        "classification": "healthcare tender notice",
        "status": "open",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "JPMC",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "180 days",
        "item_no": "1",
        "item_description": "MR-LINAC",
        "item_uom": "unit",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "items": [
            {"item_description": "MR-LINAC supply", "item_uom": "tender component", "item_quantity": "1"},
            {"item_description": "MR-LINAC installation", "item_uom": "tender component", "item_quantity": "1"},
            {"item_description": "MR-LINAC commissioning", "item_uom": "tender component", "item_quantity": "1"},
            {"item_description": "MR-LINAC maintenance", "item_uom": "tender component", "item_quantity": "1"},
        ],
        "notice_id": "TS0000006378E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000006378E",
        "query_text": "MR-LINAC, radiation oncology, medical equipment, healthcare",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-04-20",
        "closing_date": "2026-05-05",
        "title": "Purchase of Electro-Medical Equipment for Dental Department under PSDP project for financial year 2025-26 & 2026-27",
        "description": "Purchase of electro-medical equipment for the Dental Department of Federal Government Polyclinic under PSDP for FY 2025-26 and 2026-27.",
        "buyer": "Federal Government Polyclinic (PGMI)",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Federal Government Polyclinic (PGMI)",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "179 days",
        "item_no": "1",
        "item_description": "Electro-medical equipment for Dental Department",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000004608E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004608E",
        "query_text": "electro-medical equipment, dental department, polyclinic, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Complete Dental Unit", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "2", "item_description": "OPG, Cephalometric, and CBCT (all in one)", "item_quantity": "1", "item_uom": "unit"},
        ],
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-04-20",
        "closing_date": "2026-05-05",
        "title": "Purchase of Electro-Medical Equipment for Physiotherapy Department under PSDP project for financial year 2025-26 & 2026-27",
        "description": "Purchase of electro-medical equipment for the Physiotherapy Department of Federal Government Polyclinic under PSDP for FY 2025-26 and 2026-27.",
        "buyer": "Federal Government Polyclinic (PGMI)",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Federal Government Polyclinic (PGMI)",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "179 days",
        "item_no": "1",
        "item_description": "Electro-medical equipment for Physiotherapy Department",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000004609E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004609E",
        "query_text": "electro-medical equipment, physiotherapy department, polyclinic, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Pack heater", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "2", "item_description": "Traction Unit with couch", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "3", "item_description": "Short Wave Diathermy", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "4", "item_description": "UltraSound Therapy Unit", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "5", "item_description": "TENS", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "6", "item_description": "Pully Exerciser", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "7", "item_description": "Muscle stimulator with vacuum therapy", "item_quantity": "1", "item_uom": "unit"},
        ],
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-04-20",
        "closing_date": "2026-05-05",
        "title": "Purchase of Electro-Medical Equipment for Diabetic/Endocrine Department under PSDP project for financial year 2025-26 & 2026-27",
        "description": "Purchase of electro-medical equipment for the Diabetic/Endocrine Department of Federal Government Polyclinic under PSDP for FY 2025-26 and 2026-27.",
        "buyer": "Federal Government Polyclinic (PGMI)",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Federal Government Polyclinic (PGMI)",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "179 days",
        "item_no": "1",
        "item_description": "Electro-medical equipment for Diabetic/Endocrine Department",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000004610E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004610E",
        "query_text": "electro-medical equipment, diabetic, endocrine, polyclinic, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Ankle/TOE Brachial Index Probe", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "2", "item_description": "Autoclave Hybrid", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "3", "item_description": "CAD/CAM System with Milling Machine for Diabetic Orthotics", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "4", "item_description": "DEXA SCAN MACHINE", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "5", "item_description": "HERTEL EXOPHTHALMOMETER", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "6", "item_description": "Infusion pump", "item_quantity": "27", "item_uom": "units"},
            {"item_no": "7", "item_description": "OCT ANGIO", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "8", "item_description": "Ophthalmoscope", "item_quantity": "3", "item_uom": "units"},
            {"item_no": "9", "item_description": "Patient Examination Couch/Strecher", "item_quantity": "4", "item_uom": "units"},
            {"item_no": "10", "item_description": "Doppler Enable Ultrasound Machine with Different Probes", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "11", "item_description": "BMI Stadiometer", "item_quantity": "3", "item_uom": "units"},
            {"item_no": "12", "item_description": "Vital Sign Monitor", "item_quantity": "6", "item_uom": "units"},
        ],
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-04-20",
        "closing_date": "2026-05-05",
        "title": "Purchase of Electro-Medical Equipment for Ophthalmology Department under PSDP project for financial year 2025-26 & 2026-27",
        "description": "Purchase of electro-medical equipment for the Ophthalmology Department of Federal Government Polyclinic under PSDP for FY 2025-26 and 2026-27.",
        "buyer": "Federal Government Polyclinic (PGMI)",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Federal Government Polyclinic (PGMI)",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "179 days",
        "item_no": "1",
        "item_description": "Electro-medical equipment for Ophthalmology Department",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000004613E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004613E",
        "query_text": "electro-medical equipment, ophthalmology department, polyclinic, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Posterior Vitrectomy Machine with Laser", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "2", "item_description": "OCT ANGIO with FFA", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "3", "item_description": "Operating Microscope with BIOM/RESIGHT", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "4", "item_description": "Optical Biometer", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "5", "item_description": "Corneal Topography Machine", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "6", "item_description": "CXL System", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "7", "item_description": "Yag Laser", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "8", "item_description": "Green laser Photo Coagulator", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "9", "item_description": "Auto Ref Keratometer with Pachymeter", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "10", "item_description": "Ophthalmic Unit", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "11", "item_description": "Visual Acuity System", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "12", "item_description": "Slit Lamp with Tonometer", "item_quantity": "3", "item_uom": "units"},
            {"item_no": "13", "item_description": "90D lenses / Gonio Lens", "item_quantity": "1", "item_uom": "set"},
            {"item_no": "14", "item_description": "Hand Held Applanation Tonometer", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "15", "item_description": "Bipolar Electric Cautery Unit", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "16", "item_description": "Visual Field Analyser", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "17", "item_description": "DCR / Glaucoma / Cataract / Squint sets", "item_quantity": "1", "item_uom": "set"},
            {"item_no": "18", "item_description": "Phacoemulsification Unit with Accessories", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "19", "item_description": "Argon Laser", "item_quantity": "1", "item_uom": "unit"},
        ],
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-04-20",
        "closing_date": "2026-05-05",
        "title": "Purchase of Electro-Medical Equipment for Anesthesia Department under PSDP project for financial year 2025-26 & 2026-27",
        "description": "Purchase of electro-medical equipment for the Anesthesia Department of Federal Government Polyclinic under PSDP for FY 2025-26 and 2026-27.",
        "buyer": "Federal Government Polyclinic (PGMI)",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Federal Government Polyclinic (PGMI)",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "179 days",
        "item_no": "1",
        "item_description": "Electro-medical equipment for Anesthesia Department",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000004615E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004615E",
        "query_text": "electro-medical equipment, anesthesia department, polyclinic, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Anesthesia Workstation", "item_quantity": "4", "item_uom": "units"},
            {"item_no": "2", "item_description": "General Electrohydraulic Operating Table", "item_quantity": "4", "item_uom": "units"},
        ],
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-04-20",
        "closing_date": "2026-05-05",
        "title": "Purchase of Electro-Medical Equipment for Orthopedic Department under PSDP project for financial year 2025-26 & 2026-27",
        "description": "Purchase of electro-medical equipment for the Orthopedic Department of Federal Government Polyclinic under PSDP for FY 2025-26 and 2026-27.",
        "buyer": "Federal Government Polyclinic (PGMI)",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Federal Government Polyclinic (PGMI)",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "179 days",
        "item_no": "1",
        "item_description": "Electro-medical equipment for Orthopedic Department",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000004635E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004635E",
        "query_text": "electro-medical equipment, orthopedic department, polyclinic, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Orthopedic Operating Table", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "2", "item_description": "Cautery Unit", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "3", "item_description": "2D Operative Arthroscopy Tower", "item_quantity": "2", "item_uom": "units"},
        ],
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-04-20",
        "closing_date": "2026-05-05",
        "title": "Purchase of Electro-Medical Equipment for Gynecology & Obstetrics Department under PSDP project for financial year 2025-26 & 2026-27",
        "description": "Purchase of electro-medical equipment for the Gynecology and Obstetrics Department of Federal Government Polyclinic under PSDP for FY 2025-26 and 2026-27.",
        "buyer": "Federal Government Polyclinic (PGMI)",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Federal Government Polyclinic (PGMI)",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "179 days",
        "item_no": "1",
        "item_description": "Electro-medical equipment for Gynecology and Obstetrics Department",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000004612E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004612E",
        "query_text": "electro-medical equipment, gynecology, obstetrics, polyclinic, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Operative Hysteroscope with Resectoscope", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "2", "item_description": "Colposcope with Gynae Chair", "item_quantity": "4", "item_uom": "units"},
            {"item_no": "3", "item_description": "CTG Machine", "item_quantity": "2", "item_uom": "units"},
        ],
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-04-20",
        "closing_date": "2026-05-05",
        "title": "Purchase of Electro-Medical Equipment for Urology Department under PSDP project for financial year 2025-26 & 2026-27",
        "description": "Purchase of electro-medical equipment for the Urology Department of Federal Government Polyclinic under PSDP for FY 2025-26 and 2026-27.",
        "buyer": "Federal Government Polyclinic (PGMI)",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Federal Government Polyclinic (PGMI)",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "179 days",
        "item_no": "1",
        "item_description": "Electro-medical equipment for Urology Department",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000004636E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004636E",
        "query_text": "electro-medical equipment, urology department, polyclinic, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Resectoscope adult complete set", "item_quantity": "3", "item_uom": "sets"},
            {"item_no": "2", "item_description": "Cystoscope set", "item_quantity": "3", "item_uom": "sets"},
            {"item_no": "3", "item_description": "Urethrotome complete", "item_quantity": "3", "item_uom": "sets"},
            {"item_no": "4", "item_description": "Uretero-renoscope (Semirigid)", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "5", "item_description": "Holmium Laser 100 watt or higher", "item_quantity": "2", "item_uom": "units"},
        ],
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-04-20",
        "closing_date": "2026-05-05",
        "title": "Purchase of Electro-Medical Equipment for Paeds Department under PSDP project for financial year 2025-26 & 2026-27",
        "description": "Purchase of electro-medical equipment for the Paeds Department of Federal Government Polyclinic under PSDP for FY 2025-26 and 2026-27.",
        "buyer": "Federal Government Polyclinic (PGMI)",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Federal Government Polyclinic (PGMI)",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "179 days",
        "item_no": "1",
        "item_description": "Electro-medical equipment for Paeds Department",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000004637E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004637E",
        "query_text": "electro-medical equipment, paeds department, polyclinic, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "ECHO Machine", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "2", "item_description": "Ultrasonic Heavy Duty Nebulizer", "item_quantity": "1", "item_uom": "unit"},
        ],
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-04-20",
        "closing_date": "2026-05-05",
        "title": "Purchase of Electro-Medical Equipment for Medicine Department under PSDP project for financial year 2025-26 & 2026-27",
        "description": "Purchase of electro-medical equipment for the Medicine Department of Federal Government Polyclinic under PSDP for FY 2025-26 and 2026-27.",
        "buyer": "Federal Government Polyclinic (PGMI)",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Federal Government Polyclinic (PGMI)",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "179 days",
        "item_no": "1",
        "item_description": "Electro-medical equipment for Medicine Department",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000004639E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004639E",
        "query_text": "electro-medical equipment, medicine department, polyclinic, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Ventilator", "item_quantity": "4", "item_uom": "units"},
            {"item_no": "2", "item_description": "Dialysis Machine", "item_quantity": "7", "item_uom": "units"},
            {"item_no": "3", "item_description": "Fiber Optics Bronchoscope", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "4", "item_description": "Ultrasound Machine (Muscoskeletal)", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "5", "item_description": "Capillaroscope", "item_quantity": "1", "item_uom": "unit"},
        ],
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-02-23",
        "closing_date": "2026-03-12",
        "title": "Daily Local Purchase of Medicines, Disposables Lab kits and Implants",
        "description": "Daily local purchase of medicines, disposables, lab kits and implants for Combined Military Hospital Peshawar.",
        "buyer": "Combined Military Hospital Peshawar",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Combined Military Hospital Peshawar",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "365 days",
        "item_no": "1",
        "item_description": "Medicines, disposables, lab kits and implants",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "items": [
            {"item_description": "Medicines", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Disposables", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Lab kits", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Implants", "item_uom": "tender category", "item_quantity": "1"},
        ],
        "notice_id": "TS0000001422E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000001422E",
        "query_text": "medicines, disposables, lab kits, implants, hospital, medical, healthcare",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-02-26",
        "closing_date": "2026-03-26",
        "title": "Daily Local Purchase Contract of Medical Stores (Medicines / Disposables / Lab Kits / Implants) - FY 2026/27",
        "description": "Daily local purchase contract of medical stores for Combined Military Hospital Attock, including medicines, disposables, lab kits and implants.",
        "buyer": "Combined Military Hospital Attock",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Combined Military Hospital Attock",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "365 days",
        "item_no": "1",
        "item_description": "Medical stores items including medicines, disposables, lab kits and implants",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "items": [
            {"item_description": "Medicines", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Disposables", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Lab kits", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Implants", "item_uom": "tender category", "item_quantity": "1"},
        ],
        "notice_id": "TS0000001607E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000001607E",
        "query_text": "medical stores, medicines, disposables, lab kits, implants, hospital, healthcare",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-03-09",
        "closing_date": "2026-03-26",
        "title": "Daily LP Contract (Medicines / Disposables / Lab Kits / Implants) FY 2026/27",
        "description": "Daily LP contract for medicines, disposables, lab kits, and implants at Combined Military Hospital Gilgit.",
        "buyer": "Combined Military Hospital (CMH) Gilgit",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Combined Military Hospital (CMH) Gilgit",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "15 days",
        "item_no": "1",
        "item_description": "Daily LP contract for medicines, disposables, lab kits, and implants",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "items": [
            {"item_description": "Medicines", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Disposables", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Lab kits", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Implants", "item_uom": "tender category", "item_quantity": "1"},
        ],
        "notice_id": "TS0000002109E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000002109E",
        "query_text": "medicines, disposables, lab kits, implants, cmh gilgit, hospital, medical, healthcare",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-02-28",
        "closing_date": "2026-03-16",
        "title": "Daily LP Contract (Medicines / Disposables / Lab Kits / Implants) FY 2026/27",
        "description": "Daily LP contract for medicines, disposables, lab kits, and implants at Combined Military Hospital Rawalakot.",
        "buyer": "Combined Military Hospital (CMH) Rawalakot",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Combined Military Hospital (CMH) Rawalakot",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "365 days",
        "item_no": "1",
        "item_description": "Daily LP contract for medicines, disposables, lab kits, and implants",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "items": [
            {"item_description": "Medicines", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Disposables", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Lab kits", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Implants", "item_uom": "tender category", "item_quantity": "1"},
        ],
        "notice_id": "TS0000001639E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000001639E",
        "query_text": "medicines, disposables, lab kits, implants, cmh rawalakot, hospital, medical, healthcare",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-04-09",
        "closing_date": "2026-04-24",
        "title": "CMH Zhob Daily LP Contract (Medicines/Disposables/Lab kits/Implants FY 2026/2027)",
        "description": "Daily LP medicines contract for Combined Military Hospital Zhob.",
        "buyer": "Main Medical Store, CMH Zhob",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Main Medical Store, CMH Zhob",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "15 days",
        "item_no": "1",
        "item_description": "Daily LP medicines contract",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "items": [
            {"item_description": "Medicines", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Disposables", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Lab kits", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Implants", "item_uom": "tender category", "item_quantity": "1"},
        ],
        "notice_id": "TS0000003918E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000003918E",
        "query_text": "daily lp medicines, cmh zhob, hospital, medical, healthcare",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-02-27",
        "closing_date": "2026-03-14",
        "title": "Daily LP Contract (Medicines/Disposables/Lab kits/Implants FY 2026-27)",
        "description": "Daily LP medicines contract for Combined Military Hospital Dera Ismail Khan.",
        "buyer": "Medical Store, Combined Military Hospital (CMH) Dera Ismail Khan",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Medical Store, Combined Military Hospital (CMH) Dera Ismail Khan",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "26 days",
        "item_no": "1",
        "item_description": "Daily LP medicines contract",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "items": [
            {"item_description": "Medicines", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Disposables", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Lab kits", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Implants", "item_uom": "tender category", "item_quantity": "1"},
        ],
        "notice_id": "TS0000001669E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000001669E",
        "query_text": "daily lp medicines, cmh dera ismail khan, hospital, medical, healthcare",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-03-10",
        "closing_date": "2026-03-25",
        "title": "Daily LP Contract of Medical Stores (Medicines/Disposables/Lab Kits/Implants) - FY 2026/27",
        "description": "Daily LP contract of medical stores for Combined Military Hospital Sargodha.",
        "buyer": "Main Medical Store, Combined Military Hospital (CMH) Sargodha",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Main Medical Store, Combined Military Hospital (CMH) Sargodha",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "",
        "item_no": "1",
        "item_description": "Daily LP contract of medical stores",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "items": [
            {"item_description": "Medicines", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Disposables", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Lab kits", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Implants", "item_uom": "tender category", "item_quantity": "1"},
        ],
        "notice_id": "TS0000002223E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000002223E",
        "query_text": "daily lp contract of medical stores, cmh sargodha, hospital, medical, healthcare",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-04-16",
        "closing_date": "2026-05-07",
        "title": "Combined Military Hospital Mardan Bulk Purchase of PVMS, NIV / NIF Medicines, Disposable items and Lab Kits Reagents FY-2026/2027",
        "description": "Bulk purchase of medicines, disposable items, and lab kits reagents for Combined Military Hospital Mardan.",
        "buyer": "Medical Store, Combined Military Hospital (CMH) Mardan",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Medical Store, Combined Military Hospital (CMH) Mardan",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "365 days",
        "item_no": "1",
        "item_description": "Bulk purchase of medicines, disposable items, and lab kits reagents",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "items": [
            {"item_description": "Medicines", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Disposable items", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Lab kits / reagents", "item_uom": "tender category", "item_quantity": "1"},
        ],
        "notice_id": "TS0000004475E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004475E",
        "query_text": "bulk purchase medicines disposable items lab kits reagents, cmh mardan, hospital, medical, healthcare",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-04-30",
        "closing_date": "2026-05-20",
        "title": "Armed Forces Bone Marrow Transplant Center Bulk LP",
        "description": "Bulk LP for medicine, surgical disposables, and lab items at Armed Forces Bone Marrow Transplant Centre, Rawalpindi.",
        "buyer": "Armed Forces Bone Marrow Transplant Centre",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Armed Forces Bone Marrow Transplant Centre",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "365 days",
        "item_no": "1",
        "item_description": "Bulk LP for medicine, surgical disposables, and lab items",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "items": [
            {"item_description": "Medicines", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Surgical disposables", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Lab items", "item_uom": "tender category", "item_quantity": "1"},
        ],
        "notice_id": "TS0000005273E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000005273E",
        "query_text": "bulk lp medicine surgical disposables lab items, afbmtc, rawalpindi, medical, healthcare",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-04-29",
        "closing_date": "2026-05-14",
        "title": "Contract of Daily Local Purchase Medicine",
        "description": "Daily local purchase medicine contract for Armed Forces Bone Marrow Transplant Centre, Combined Military Hospital Rawalpindi.",
        "buyer": "Armed Forces Bone Marrow Transplant Centre, Combined Military Hospital Rawalpindi",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Armed Forces Bone Marrow Transplant Centre, Combined Military Hospital Rawalpindi",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "365 days",
        "item_no": "1",
        "item_description": "Daily local purchase medicine contract",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000005255E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000005255E",
        "query_text": "daily local purchase medicine, armed forces bone marrow transplant centre, cmh rawalpindi, hospital, medical, healthcare",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-02-23",
        "closing_date": "2026-03-17",
        "title": "Daily LP Contract (Medicines/Disposables/Lab Kits/Implants) - FY 2026-27",
        "description": "Daily LP contract for medicines, disposables, lab kits, and implants at Combined Military Hospital Chhor Cantt, Umerkot.",
        "buyer": "Combined Military Hospital Chhor Cantt",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Combined Military Hospital Chhor Cantt",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "15 days",
        "item_no": "1",
        "item_description": "Medicines, disposables, lab kits, and implants",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "items": [
            {"item_description": "Medicines", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Disposables", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Lab kits", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Implants", "item_uom": "tender category", "item_quantity": "1"},
        ],
        "notice_id": "TS0000001388E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000001388E",
        "query_text": "medicines, disposables, lab kits, implants, cmh chhor, hospital, medical, healthcare",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-03-16",
        "closing_date": "2026-03-31",
        "title": "Daily LP Contract FY 2026-27",
        "description": "Daily LP contract for Combined Military Hospital Mangla Cantt medical store.",
        "buyer": "Combined Military Hospital Mangla Cantt",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Combined Military Hospital Mangla Cantt",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "15 days",
        "item_no": "1",
        "item_description": "Daily LP contract for medical store",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000002590E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000002590E",
        "query_text": "daily lp contract, medical store, cmh mangla, hospital, medical, healthcare",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-03-16",
        "closing_date": "2026-03-31",
        "title": "DAILY LOCAL PURCHASE TENDER FY 2026-27 CMH KHARIAN (MEDICINES, DISPOSABLES, APPLIANCES, EM EQPT, LAB KITS, IMPLANTS)",
        "description": "Daily local purchase tender for CMH Kharian covering medicines, disposables, appliances, electro-medical equipment, lab kits and implants.",
        "buyer": "Army Medical Corps / Combined Military Hospital (CMH) Kharian",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Combined Military Hospital Kharian",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "365 days",
        "item_no": "1",
        "item_description": "Medicines, disposables, appliances, electro-medical equipment, lab kits and implants",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "items": [
            {"item_description": "Medicines", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Disposables", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Appliances", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Electro-medical equipment", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Lab kits", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Implants", "item_uom": "tender category", "item_quantity": "1"},
        ],
        "notice_id": "TS0000002571E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000002571E",
        "query_text": "medicines, disposables, appliances, electro-medical equipment, lab kits, implants, hospital, healthcare",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-05-08",
        "closing_date": "2026-06-02",
        "title": "Tender for the purchase of Medicines & Injectable Items",
        "description": "Annual running rate contract basis tender for medicines and injectable items for tertiary and secondary care hospitals under PAEC General Hospital Islamabad.",
        "buyer": "Pakistan Atomic Energy Commission (PAEC) / PAEC General Hospital Islamabad",
        "classification": "healthcare tender notice",
        "status": "published",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "PAEC General Hospital Islamabad",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "365 days",
        "item_no": "1",
        "item_description": "Medicines and injectable items on annual running rate contract basis",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "items": [
            {"item_description": "Medicines", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Injectable items", "item_uom": "tender category", "item_quantity": "1"},
        ],
        "notice_id": "TS0000005880E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000005880E",
        "query_text": "medicines, injectable items, hospital, healthcare, PAEC",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-04-10",
        "closing_date": "2026-05-12",
        "title": "DAILY LP CONTRACT OF (MEDICINE/DISPOSABLES/LAB KITS/IMPLANTS) CMH BANNU",
        "description": "Daily LP contract for medicines, disposables, lab kits and implants for Combined Military Hospital Bannu for FY 2026-2027.",
        "buyer": "Ministry of Defence / Combined Military Hospital Bannu",
        "classification": "healthcare tender notice",
        "status": "published",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Combined Military Hospital Bannu",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "1 year",
        "item_no": "1",
        "item_description": "Medicines, disposables, lab kits and implants for FY 2026-2027",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "items": [
            {"item_description": "Medicines", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Disposables", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Lab kits", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Implants", "item_uom": "tender category", "item_quantity": "1"},
        ],
        "notice_id": "TS0000004014E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004014E",
        "query_text": "medicines, disposables, lab kits, implants, CMH Bannu, hospital, medical, healthcare",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-03-12",
        "closing_date": "2026-03-30",
        "title": "Daily LP Contract of Medicines FY 2026-27 CMH JHELUM",
        "description": "Daily LP contract of medicines for Combined Military Hospital Jhelum for FY 2026-27.",
        "buyer": "Combined Military Hospital Jhelum",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Combined Military Hospital Jhelum",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "1 year",
        "item_no": "1",
        "item_description": "Daily LP contract of medicines for FY 2026-27",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000002213E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000002213E",
        "query_text": "medicines, CMH Jhelum, hospital, medical, healthcare",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-03-03",
        "closing_date": "2026-04-09",
        "title": "Daily LP Contract FY 2026/27",
        "description": "Daily LP contract of medicines, disposables and lab kits for Combined Military Hospital Skardu for FY 2026-27.",
        "buyer": "Ministry of Defence / Combined Military Hospital Skardu",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Combined Military Hospital Skardu",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "1 year",
        "item_no": "1",
        "item_description": "Medicines, disposables and lab kits for FY 2026-27",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "items": [
            {"item_description": "Medicines", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Disposables", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Lab kits", "item_uom": "tender category", "item_quantity": "1"},
        ],
        "notice_id": "TS0000001795E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000001795E",
        "query_text": "medicines, disposables, lab kits, CMH Skardu, hospital, medical, healthcare",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-03-19",
        "closing_date": "2026-04-07",
        "title": "CONTRACT FOR DAILY LP OF MEDICINES CMH MUZAFFARABAD FY 2026-27",
        "description": "Contract for daily local purchase of medicines for Combined Military Hospital Muzaffarabad for FY 2026-27.",
        "buyer": "Ministry of Defence / Combined Military Hospital Muzaffarabad",
        "classification": "healthcare tender notice",
        "status": "published",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Combined Military Hospital Muzaffarabad",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "1 year",
        "item_no": "1",
        "item_description": "Daily required medicines for FY 2026-27",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000002924E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000002924E",
        "query_text": "medicines, CMH Muzaffarabad, hospital, medical, healthcare",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-02-27",
        "closing_date": "2026-03-25",
        "title": "Daily Local Purchase Contract (Medicines/Disposable/Lab Kits/Implants) FY 2026/27",
        "description": "Daily local purchase contract for medicines, disposables, lab kits and implants for Combined Military Hospital Sibi for FY 2026-27.",
        "buyer": "Ministry of Defence / Combined Military Hospital Sibi",
        "classification": "healthcare tender notice",
        "status": "published",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Combined Military Hospital Sibi",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "1 year",
        "item_no": "1",
        "item_description": "Medicines, disposables, lab kits and implants for FY 2026-27",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "items": [
            {"item_description": "Medicines", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Disposables", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Lab kits", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Implants", "item_uom": "tender category", "item_quantity": "1"},
        ],
        "notice_id": "TS0000001708E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000001708E",
        "query_text": "medicines, disposables, lab kits, implants, CMH Sibi, hospital, medical, healthcare",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-02-12",
        "closing_date": "2026-03-02",
        "title": "Different Medical Equipment and Furniture & Fixture",
        "description": "Tender for different medical equipment and furniture and fixtures for PAEC General Hospital.",
        "buyer": "Pakistan Atomic Energy Commission (PAEC) / PAEC General Hospital",
        "classification": "healthcare tender notice",
        "status": "published",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "PAEC General Hospital",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "",
        "item_no": "1",
        "item_description": "Different medical equipment and furniture and fixtures",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000000875E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000000875E",
        "query_text": "medical equipment, furniture, fixture, PAEC general hospital, hospital, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Medical equipment", "item_quantity": "1", "item_uom": "category"},
            {"item_no": "2", "item_description": "Furniture and fixtures", "item_quantity": "1", "item_uom": "category"},
        ],
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-02-24",
        "closing_date": "2026-03-12",
        "title": "Daily LP Contract of Medicines Fy 2026-27",
        "description": "Requirement of bids for daily LP contract of medicines for Combined Military Hospital Dera Nawab Sahib for FY 2026-27.",
        "buyer": "Ministry of Defence / Combined Military Hospital Dera Nawab Sahib",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Combined Military Hospital Dera Nawab Sahib",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "1 year",
        "item_no": "1",
        "item_description": "Daily LP contract of medicines for FY 2026-27",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000001459E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000001459E",
        "query_text": "medicines, CMH Dera Nawab Sahib, hospital, medical, healthcare",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-02-25",
        "closing_date": "2026-03-15",
        "title": "DLP Contract FY2026-27 - CMH Chunian",
        "description": "Daily local purchase contract for medicines, surgical disposables, lab reagents and medical consumables for Combined Military Hospital Chunian for FY 2026-27.",
        "buyer": "Ministry of Defence / Combined Military Hospital Chunian",
        "classification": "healthcare tender notice",
        "status": "published",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Combined Military Hospital Chunian",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "1 year",
        "item_no": "1",
        "item_description": "Medicines, surgical disposables, lab reagents and medical consumables for FY 2026-27",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "items": [
            {"item_description": "Medicines", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Surgical disposables", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Lab reagents", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Medical consumables", "item_uom": "tender category", "item_quantity": "1"},
        ],
        "notice_id": "TS0000001530E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000001530E",
        "query_text": "medicines, surgical disposables, lab reagents, medical consumables, CMH Chunian, hospital, medical, healthcare",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-04-19",
        "closing_date": "2026-05-05",
        "title": "DAILY LOCAL PURCHASE TENDER FY 2026-27 CMH KHARIAN (MEDICINES,DISPOSABLES,APPLIANCES,EM EQPT,LAB KITS, IMPLANTS)",
        "description": "Daily local purchase tender for medicines, disposables, appliances, electro-medical equipment, lab kits and implants for Combined Military Hospital Kharian for FY 2026-27.",
        "buyer": "Combined Military Hospital Kharian",
        "classification": "healthcare tender notice",
        "status": "published",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Combined Military Hospital Kharian",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "1 year",
        "item_no": "1",
        "item_description": "Medicines, disposables, appliances, electro-medical equipment, lab kits and implants for FY 2026-27",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "items": [
            {"item_description": "Medicines", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Disposables", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Appliances", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Electro-medical equipment", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Lab kits", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Implants", "item_uom": "tender category", "item_quantity": "1"},
        ],
        "notice_id": "TS0000004566E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004566E",
        "query_text": "medicines, disposables, electro-medical equipment, lab kits, implants, CMH Kharian, hospital, medical, healthcare",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-03-30",
        "closing_date": "2026-04-16",
        "title": "Daily LP Contract of Medical Stores (Medicine/Disposables/Lab Kits/Implants) - FY 2026-27",
        "description": "Daily LP contract of medicines, disposables, lab kits and implants for Combined Military Hospital Lahore for FY 2026-27.",
        "buyer": "Combined Military Hospital Lahore",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Combined Military Hospital Lahore",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "30 days",
        "item_no": "1",
        "item_description": "Daily LP contract of medical stores including medicines, disposables, lab kits and implants for FY 2026-27",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "items": [
            {"item_description": "Medicines", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Disposables", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Lab kits", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Implants", "item_uom": "tender category", "item_quantity": "1"},
        ],
        "notice_id": "TS0000003335E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000003335E",
        "query_text": "medicines, disposables, lab kits, implants, CMH Lahore, hospital, medical, healthcare",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-04-18",
        "closing_date": "2026-05-06",
        "title": "Proc of Electro Medical Equipment & Misc Items",
        "description": "Tender notice covering electro medical equipment and related daily local purchase medicines and medical gases for PAC Hospital Kamra.",
        "buyer": "PAC Hospital Kamra",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "PAC Hospital Kamra",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "120 days",
        "item_no": "1",
        "item_description": "Electro medical equipment and related daily local purchase medicines and medical gases",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "items": [
            {"item_description": "Electro medical equipment", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Medicines", "item_uom": "tender category", "item_quantity": "1"},
            {"item_description": "Medical gases", "item_uom": "tender category", "item_quantity": "1"},
        ],
        "notice_id": "TS0000004537E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004537E",
        "query_text": "electro medical equipment, medicines, medical gases, PAC Hospital Kamra, hospital, medical, healthcare",
    },
    {
        "source": "PPRA Public Tender Notice Fallback",
        "country": "Pakistan",
        "country_code": "PK",
        "publication_date": "2026-04-25",
        "closing_date": "2026-05-13",
        "title": "Electro Medical Equipment",
        "description": "Tender for electro medical equipment from Pakistan Navy Medical Store Depot at PNS Shifa, Karachi.",
        "buyer": "Pakistan Navy Medical Store Depot (PNMSD)",
        "classification": "healthcare tender notice",
        "status": "closed",
        "currency": "",
        "amount": "",
        "awarding_agency_name": "Pakistan Navy Medical Store Depot (PNMSD)",
        "supplier_name": "",
        "awarded_date": "",
        "awarded_value_detail": "",
        "contract_period": "15 days",
        "item_no": "1",
        "item_description": "Electro medical equipment",
        "item_uom": "tender package",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "",
        "notice_id": "TS0000004946E",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004946E",
        "query_text": "electro medical equipment, PNMSD, PNS Shifa, hospital, medical, healthcare",
    },
]
