from __future__ import annotations

VERIFIED_SEED_TENDERS = [
    {
        "title": "Tender for purchase of Equipment, Chemicals and Consumables for mRNA Technology Transfer out of M.P.P Funds for National Institute of Health, Islamabad",
        "publication_date": "2026-03-09",
        "closing_date": "2026-04-02",
        "buyer": "National Institutes of Health (NIH)",
        "contract_period": "120 days",
        "classification": "healthcare tender document",
        "status": "closed",
        "notice_id": "P9695",
        "notice_url": "https://pa.epads.gov.pk/procurement/goods/328/sbd",
        "description": "Procurement of equipment, chemicals and consumables for mRNA technology transfer at the National Institutes of Health, Islamabad.",
        "query_text": "mRNA technology transfer, equipment, chemicals, consumables, laboratory, medical, healthcare, nih",
        "items": [
            {"item_no": "1", "item_description": "Precision balance", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "2", "item_description": "Vertical Pressure Steam Autoclave", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "3", "item_description": "Nitrogen Flush System", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "4", "item_description": "Conductivity meter", "item_quantity": "3", "item_uom": "units"},
            {"item_no": "5", "item_description": "Shaking Incubator", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "6", "item_description": "Ultrasonic bath", "item_quantity": "3", "item_uom": "units"},
            {"item_no": "7", "item_description": "Vortex mixer", "item_quantity": "4", "item_uom": "units"},
            {"item_no": "8", "item_description": "Incubator", "item_quantity": "3", "item_uom": "units"},
            {"item_no": "9", "item_description": "Nano Centrifuge", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "10", "item_description": "Macroman Pipette aid", "item_quantity": "4", "item_uom": "units"},
            {"item_no": "11", "item_description": "Ice Flaker machine", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "12", "item_description": "Heating Block", "item_quantity": "5", "item_uom": "units"},
            {"item_no": "13", "item_description": "Microplate orbital shaker", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "14", "item_description": "Fumehood", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "15", "item_description": "Fridge / Freezer (-20C)", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "16", "item_description": "-80C Freezer", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "17", "item_description": "Microwave", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "18", "item_description": "BioSafety Cabinet", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "19", "item_description": "Aspiration System", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "20", "item_description": "Digital 3D Shaker", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "21", "item_description": "Peristaltic Pump", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "22", "item_description": "Basic Lab Consumables", "item_quantity": "1", "item_uom": "lot"},
            {"item_no": "23", "item_description": "Raw materials", "item_quantity": "1", "item_uom": "lot"},
            {"item_no": "24", "item_description": "Consumables", "item_quantity": "1", "item_uom": "lot"},
        ],
    },
    {
        "title": "Purchase of Electro-Medical Equipment for Diabetic/Endocrine Department under PSDP project for financial year 2025-26 & 2026-27",
        "publication_date": "2026-04-20",
        "closing_date": "2026-05-05",
        "buyer": "Federal Government Polyclinic (PGMI)",
        "contract_period": "",
        "classification": "healthcare tender document",
        "status": "closed",
        "notice_id": "P22442",
        "notice_url": "https://pa.epads.gov.pk/procurement/goods/13075/sbd",
        "description": "Purchase of electro-medical equipment for the Diabetic/Endocrine Department of Federal Government Polyclinic under PSDP for FY 2025-26 and 2026-27.",
        "query_text": "electro-medical equipment, diabetic, endocrine, polyclinic, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Ankle/TOE Brachial Index Probe", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "2", "item_description": "Autoclave Hybrid", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "3", "item_description": "CAD/CAM System with Milling Machine for Diabetic Orthotics", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "4", "item_description": "DEXA SCAN MACHINE", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "5", "item_description": "HERTEL EXOPHTHALMOMETER", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "6", "item_description": "Infusion pump", "item_quantity": "27", "item_uom": "units"},
            {"item_no": "7", "item_description": "OCT ANGIO", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "8", "item_description": "Ophthalmoscope", "item_quantity": "3", "item_uom": "units"},
            {"item_no": "9", "item_description": "Patient Examination Couch/Strecher", "item_quantity": "4", "item_uom": "units"},
            {"item_no": "10", "item_description": "Doppler Enable Ultrasound Machine with Different Probes", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "11", "item_description": "BMI Stadiometer", "item_quantity": "3", "item_uom": "units"},
            {"item_no": "12", "item_description": "Vital Sign Monitor", "item_quantity": "6", "item_uom": "units"},
        ],
    },
    {
        "title": "Purchase of Electro-Medical Equipment for Surgery Department under PSDP project for financial year 2025-26 & 2026-27",
        "publication_date": "2026-04-20",
        "closing_date": "2026-05-05",
        "buyer": "Federal Government Polyclinic (PGMI)",
        "contract_period": "",
        "classification": "healthcare tender document",
        "status": "closed",
        "notice_id": "P22463",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004606E",
        "description": "Purchase of electro-medical equipment for the Surgery Department of Federal Government Polyclinic under PSDP for FY 2025-26 and 2026-27.",
        "query_text": "electro-medical equipment, surgery department, polyclinic, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "3D Laparoscopic Unit with basic set", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "2", "item_description": "4K Laparoscopy Camera Complete Tower", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "3", "item_description": "Blood Warmer", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "4", "item_description": "Cautery Unit", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "5", "item_description": "Choledochoscope", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "6", "item_description": "Dermatome with accessories", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "7", "item_description": "Flexible Sigmoidoscope", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "8", "item_description": "Laparoscopic Bariatric Set", "item_quantity": "1", "item_uom": "set"},
            {"item_no": "9", "item_description": "Laparoscopic Stapling Gun", "item_quantity": "8", "item_uom": "units"},
            {"item_no": "10", "item_description": "Laser Machine with accessories", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "11", "item_description": "Ligasure Hand Pieces", "item_quantity": "50", "item_uom": "pieces"},
            {"item_no": "12", "item_description": "Ligasure Hand Pieces Open", "item_quantity": "50", "item_uom": "pieces"},
            {"item_no": "13", "item_description": "Nerve Stimulator", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "14", "item_description": "Open Stapling Gun", "item_quantity": "30", "item_uom": "units"},
            {"item_no": "15", "item_description": "Portable Ultrasound", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "16", "item_description": "Sterilization Solution Sprayer", "item_quantity": "4", "item_uom": "units"},
            {"item_no": "17", "item_description": "Heavy Duty Suction Machine", "item_quantity": "4", "item_uom": "units"},
            {"item_no": "18", "item_description": "Thomas Splint Adult Young Large Size", "item_quantity": "10", "item_uom": "units"},
            {"item_no": "19", "item_description": "Vascular Clamp Set", "item_quantity": "2", "item_uom": "sets"},
            {"item_no": "20", "item_description": "Vessel Sealer Generator", "item_quantity": "1", "item_uom": "unit"},
        ],
    },
    {
        "title": "Purchase of Electro-Medical Equipment for Dental Department under PSDP project for financial year 2025-26 & 2026-27",
        "publication_date": "2026-04-20",
        "closing_date": "2026-05-05",
        "buyer": "Federal Government Polyclinic (PGMI)",
        "contract_period": "",
        "classification": "healthcare tender document",
        "status": "closed",
        "notice_id": "P22431",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004608E",
        "description": "Purchase of electro-medical equipment for the Dental Department of Federal Government Polyclinic under PSDP for FY 2025-26 and 2026-27.",
        "query_text": "electro-medical equipment, dental department, polyclinic, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Complete Dental Unit", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "2", "item_description": "OPG, Cephalometric, and CBCT (all in one)", "item_quantity": "1", "item_uom": "unit"},
        ],
    },
    {
        "title": "Purchase of Electro-Medical Equipment for Physiotherapy Department under PSDP project for financial year 2025-26 & 2026-27",
        "publication_date": "2026-04-20",
        "closing_date": "2026-05-05",
        "buyer": "Federal Government Polyclinic (PGMI)",
        "contract_period": "",
        "classification": "healthcare tender document",
        "status": "closed",
        "notice_id": "P22432",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004609E",
        "description": "Purchase of electro-medical equipment for the Physiotherapy Department of Federal Government Polyclinic under PSDP for FY 2025-26 and 2026-27.",
        "query_text": "electro-medical equipment, physiotherapy department, polyclinic, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Pack heater", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "2", "item_description": "Traction Unit with couch", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "3", "item_description": "Short Wave Diathermy", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "4", "item_description": "UltraSound Therapy Unit", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "5", "item_description": "TENS", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "6", "item_description": "Pully Exerciser", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "7", "item_description": "Muscle stimulator with vacuum therapy", "item_quantity": "1", "item_uom": "unit"},
        ],
    },
    {
        "title": "Purchase of Electro-Medical Equipment for Anesthesia Department under PSDP project for financial year 2025-26 & 2026-27",
        "publication_date": "2026-04-20",
        "closing_date": "2026-05-05",
        "buyer": "Federal Government Polyclinic (PGMI)",
        "contract_period": "",
        "classification": "healthcare tender document",
        "status": "closed",
        "notice_id": "P22430",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004615E",
        "description": "Purchase of electro-medical equipment for the Anesthesia Department of Federal Government Polyclinic under PSDP for FY 2025-26 and 2026-27.",
        "query_text": "electro-medical equipment, anesthesia department, polyclinic, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Anesthesia Workstation", "item_quantity": "4", "item_uom": "units"},
            {"item_no": "2", "item_description": "General Electrohydraulic Operating Table", "item_quantity": "4", "item_uom": "units"},
        ],
    },
    {
        "title": "Purchase of Electro-Medical Equipment for Gynecology & Obstetrics Department under PSDP project for financial year 2025-26 & 2026-27",
        "publication_date": "2026-04-20",
        "closing_date": "2026-05-05",
        "buyer": "Federal Government Polyclinic (PGMI)",
        "contract_period": "",
        "classification": "healthcare tender document",
        "status": "closed",
        "notice_id": "P22433",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004612E",
        "description": "Purchase of electro-medical equipment for the Gynecology and Obstetrics Department of Federal Government Polyclinic under PSDP for FY 2025-26 and 2026-27.",
        "query_text": "electro-medical equipment, gynecology, obstetrics, polyclinic, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Operative Hysteroscope with Resectoscope", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "2", "item_description": "Colposcope with Gynae Chair", "item_quantity": "4", "item_uom": "units"},
            {"item_no": "3", "item_description": "CTG Machine", "item_quantity": "2", "item_uom": "units"},
        ],
    },
    {
        "title": "Purchase of Electro-Medical Equipment for Orthopedic Department under PSDP project for financial year 2025-26 & 2026-27",
        "publication_date": "2026-04-20",
        "closing_date": "2026-05-05",
        "buyer": "Federal Government Polyclinic (PGMI)",
        "contract_period": "",
        "classification": "healthcare tender document",
        "status": "closed",
        "notice_id": "P22451",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004635E",
        "description": "Purchase of electro-medical equipment for the Orthopedic Department of Federal Government Polyclinic under PSDP for FY 2025-26 and 2026-27.",
        "query_text": "electro-medical equipment, orthopedic department, polyclinic, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Orthopedic Operating Table", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "2", "item_description": "Cautery Unit", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "3", "item_description": "2D Operative Arthroscopy Tower", "item_quantity": "2", "item_uom": "units"},
        ],
    },
    {
        "title": "Purchase of Electro-Medical Equipment for Ophthalmology Department under PSDP project for financial year 2025-26 & 2026-27",
        "publication_date": "2026-04-20",
        "closing_date": "2026-05-05",
        "buyer": "Federal Government Polyclinic (PGMI)",
        "contract_period": "",
        "classification": "healthcare tender document",
        "status": "closed",
        "notice_id": "P22436",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004613E",
        "description": "Purchase of electro-medical equipment for the Ophthalmology Department of Federal Government Polyclinic under PSDP for FY 2025-26 and 2026-27.",
        "query_text": "electro-medical equipment, ophthalmology department, polyclinic, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Posterior Vitrectomy Machine with Laser", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "2", "item_description": "OCT ANGIO with FFA", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "3", "item_description": "Operating Microscope with BIOM/RESIGHT", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "4", "item_description": "Optical Biometer", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "5", "item_description": "Corneal Topography Machine", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "6", "item_description": "CXL System", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "7", "item_description": "Yag Laser", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "8", "item_description": "Green laser Photo Coagulator", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "9", "item_description": "Auto Ref Keratometer with Pachymeter", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "10", "item_description": "Ophthalmic Unit", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "11", "item_description": "Visual Acuity System", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "12", "item_description": "Slit Lamp with Tonometer", "item_quantity": "3", "item_uom": "units"},
            {"item_no": "13", "item_description": "90D lenses / Gonio Lens", "item_quantity": "1", "item_uom": "set"},
            {"item_no": "14", "item_description": "Hand Held Applanation Tonometer", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "15", "item_description": "Bipolar Electric Cautery Unit", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "16", "item_description": "Visual Field Analyser", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "17", "item_description": "DCR / Glaucoma / Cataract / Squint sets", "item_quantity": "1", "item_uom": "set"},
            {"item_no": "18", "item_description": "Phacoemulsification Unit with Accessories", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "19", "item_description": "Argon Laser", "item_quantity": "1", "item_uom": "unit"},
        ],
    },
    {
        "title": "Purchase of Electro-Medical Equipment for Urology Department under PSDP project for financial year 2025-26 & 2026-27",
        "publication_date": "2026-04-20",
        "closing_date": "2026-05-05",
        "buyer": "Federal Government Polyclinic (PGMI)",
        "contract_period": "",
        "classification": "healthcare tender document",
        "status": "closed",
        "notice_id": "P22454",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004636E",
        "description": "Purchase of electro-medical equipment for the Urology Department of Federal Government Polyclinic under PSDP for FY 2025-26 and 2026-27.",
        "query_text": "electro-medical equipment, urology department, polyclinic, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Resectoscope adult complete set", "item_quantity": "3", "item_uom": "sets"},
            {"item_no": "2", "item_description": "Cystoscope set", "item_quantity": "3", "item_uom": "sets"},
            {"item_no": "3", "item_description": "Urethrotome complete", "item_quantity": "3", "item_uom": "sets"},
            {"item_no": "4", "item_description": "Uretero-renoscope (Semirigid)", "item_quantity": "2", "item_uom": "units"},
            {"item_no": "5", "item_description": "Holmium Laser 100 watt or higher", "item_quantity": "2", "item_uom": "units"},
        ],
    },
    {
        "title": "Purchase of Electro-Medical Equipment for Paeds Department under PSDP project for financial year 2025-26 & 2026-27",
        "publication_date": "2026-04-20",
        "closing_date": "2026-05-05",
        "buyer": "Federal Government Polyclinic (PGMI)",
        "contract_period": "",
        "classification": "healthcare tender document",
        "status": "closed",
        "notice_id": "P22460",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004637E",
        "description": "Purchase of electro-medical equipment for the Paeds Department of Federal Government Polyclinic under PSDP for FY 2025-26 and 2026-27.",
        "query_text": "electro-medical equipment, paeds department, polyclinic, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "ECHO Machine", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "2", "item_description": "Ultrasonic Heavy Duty Nebulizer", "item_quantity": "1", "item_uom": "unit"},
        ],
    },
    {
        "title": "Purchase of Electro-Medical Equipment for Medicine Department under PSDP project for financial year 2025-26 & 2026-27",
        "publication_date": "2026-04-20",
        "closing_date": "2026-05-05",
        "buyer": "Federal Government Polyclinic (PGMI)",
        "contract_period": "",
        "classification": "healthcare tender document",
        "status": "closed",
        "notice_id": "P22457",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004639E",
        "description": "Purchase of electro-medical equipment for the Medicine Department of Federal Government Polyclinic under PSDP for FY 2025-26 and 2026-27.",
        "query_text": "electro-medical equipment, medicine department, polyclinic, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Ventilator", "item_quantity": "4", "item_uom": "units"},
            {"item_no": "2", "item_description": "Dialysis Machine", "item_quantity": "7", "item_uom": "units"},
            {"item_no": "3", "item_description": "Fiber Optics Bronchoscope", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "4", "item_description": "Ultrasound Machine (Muscoskeletal)", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "5", "item_description": "Capillaroscope", "item_quantity": "1", "item_uom": "unit"},
        ],
    },
    {
        "title": "Purchase of Electro-Medical Equipment for Cardiology Department under PSDP project for financial year 2025-26 & 2026-27",
        "publication_date": "2026-04-20",
        "closing_date": "2026-05-05",
        "buyer": "Federal Government Polyclinic (PGMI)",
        "contract_period": "",
        "classification": "healthcare tender document",
        "status": "cancelled",
        "notice_id": "P22439",
        "notice_url": "https://epms.ppra.gov.pk/public/tenders/tender-details/TS0000004646E",
        "description": "Purchase of electro-medical equipment for the Cardiology Department of Federal Government Polyclinic under PSDP for FY 2025-26 and 2026-27.",
        "query_text": "electro-medical equipment, cardiology department, polyclinic, medical, healthcare",
        "items": [
            {"item_no": "1", "item_description": "Provision / Installation of Cath Lab Machine", "item_quantity": "1", "item_uom": "lot"},
            {"item_no": "2", "item_description": "Electro hydraulic moveable Beds", "item_quantity": "30", "item_uom": "beds"},
            {"item_no": "3", "item_description": "ECG Machine", "item_quantity": "16", "item_uom": "units"},
            {"item_no": "4", "item_description": "Defibrillator", "item_quantity": "9", "item_uom": "units"},
            {"item_no": "5", "item_description": "Angiography Complete system with complete accessories", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "6", "item_description": "Automatic CPR Machine with Defibrillator", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "7", "item_description": "ECHO-Cardiography", "item_quantity": "1", "item_uom": "unit"},
            {"item_no": "8", "item_description": "Portable ECHOCardiography", "item_quantity": "1", "item_uom": "unit"},
        ],
    },
]
