from __future__ import annotations

VERIFIED_SEED_TENDERS = [
    {
        "source_name": "official_drap_page_and_pdf",
        "title": "Tender for supply of chemicals, glassware, equipment and reference standards for National Control Laboratory for Biologicals (Retender)",
        "publication_date": "2024-02-14",
        "closing_date": "2024-02-28",
        "buyer": "National Control Laboratory for Biologicals, Drug Regulatory Authority of Pakistan",
        "contract_period": "FY 2023-24",
        "classification": "healthcare tender document",
        "status": "published",
        "notice_id": "tender-for-supply-of-chemicals-glassware-equipment-and-reference-standards-for-national-control-laboratory-for-biologicals-retender",
        "notice_url": "https://www.dra.gov.pk/news_updates/tenders/tender-for-supply-of-chemicals-glassware-equipment-and-reference-standards-for-national-control-laboratory-for-biologicals-retender/",
        "description": "Retender for supply of lab chemicals, glassware, equipment and reference standards for the National Control Laboratory for Biologicals, Islamabad during FY 2023-24.",
        "query_text": "laboratory, glassware, equipment, reference standard, endotoxin, medical, healthcare, retender, nclb",
        "items": [
            {"item_no": "RT24-01", "item_description": "Ampoule Cutter", "item_quantity": "05", "item_uom": "Nos"},
            {"item_no": "RT24-02", "item_description": "Vial Decaper (8mm and 11mm)", "item_quantity": "01", "item_uom": "Nos"},
            {"item_no": "RT24-03", "item_description": "Vial Decaper (13mm and 20mm)", "item_quantity": "01", "item_uom": "Nos"},
            {"item_no": "RT24-04", "item_description": "Vial Decaper (30mm)", "item_quantity": "01", "item_uom": "Nos"},
            {"item_no": "RT24-05", "item_description": "Indicator Tape for Autoclave", "item_quantity": "02", "item_uom": "Rolls"},
            {"item_no": "RT24-06", "item_description": "Powder Free gloves (Rubber quality)", "item_quantity": "50", "item_uom": "Boxes"},
            {"item_no": "RT24-07", "item_description": "Surgical Mask", "item_quantity": "50", "item_uom": "Boxes"},
            {"item_no": "RT24-08", "item_description": "Shoe cover (Plastic)", "item_quantity": "1000", "item_uom": "Pairs"},
            {"item_no": "RT24-09", "item_description": "Syringes (1mL)", "item_quantity": "10", "item_uom": "Boxes"},
            {"item_no": "RT24-10", "item_description": "Syringes (3mL)", "item_quantity": "10", "item_uom": "Boxes"},
            {"item_no": "RT24-11", "item_description": "Syringes (5mL)", "item_quantity": "10", "item_uom": "Boxes"},
            {"item_no": "RT24-12", "item_description": "Syringes (10mL)", "item_quantity": "02", "item_uom": "Boxes"},
            {"item_no": "RT24-13", "item_description": "Chloroxylenol (4.8% W/V)", "item_quantity": "10", "item_uom": "Liters"},
            {"item_no": "RT24-14", "item_description": "Rectified Spirit", "item_quantity": "50", "item_uom": "Liters"},
            {"item_no": "RT24-15", "item_description": "Iso-propyl Alcohol (70% v/v)", "item_quantity": "50", "item_uom": "Liters"},
            {"item_no": "RT24-16", "item_description": "PPE for sterility test (Autoclavable), medium size", "item_quantity": "10", "item_uom": "Units"},
            {"item_no": "RT24-17", "item_description": "PPE for sterility test (Autoclavable), large size", "item_quantity": "10", "item_uom": "Units"},
            {"item_no": "RT24-18", "item_description": "Cover slip / glass for microscopic glass slides", "item_quantity": "01", "item_uom": "Box"},
            {"item_no": "RT24-19", "item_description": "Test Tube for Bacterial Endotoxin Testing (BET)", "item_quantity": "2000", "item_uom": "Units"},
            {"item_no": "RT24-20", "item_description": "LAL Test Lysate (for Gel Clot method)", "item_quantity": "10", "item_uom": "Vials"},
            {"item_no": "RT24-21", "item_description": "LAL Water", "item_quantity": "15", "item_uom": "Bottles"},
            {"item_no": "RT24-22", "item_description": "Positive Control of Endotoxin (CSE)", "item_quantity": "05", "item_uom": "Vials"},
            {"item_no": "RT24-23", "item_description": "Filter Paper 0.22um for filtration assembly", "item_quantity": "01", "item_uom": "Pack"},
            {"item_no": "RT24-24", "item_description": "pH Buffer 4.0", "item_quantity": "01", "item_uom": "Bottle"},
            {"item_no": "RT24-25", "item_description": "pH Buffer 7.0", "item_quantity": "01", "item_uom": "Bottle"},
            {"item_no": "RT24-26", "item_description": "pH Buffer 10.0", "item_quantity": "01", "item_uom": "Bottle"},
            {"item_no": "RT24-27", "item_description": "Butter paper for weighing balance", "item_quantity": "02", "item_uom": "Packets"},
            {"item_no": "RT24-28", "item_description": "Aluminum foil", "item_quantity": "10", "item_uom": "Rolls"},
            {"item_no": "RT24-29", "item_description": "Gloves for Autoclave", "item_quantity": "02", "item_uom": "Pairs"},
            {"item_no": "RT24-30", "item_description": "Osmometer sampler tips", "item_quantity": "02", "item_uom": "Boxes"},
            {"item_no": "RT24-31", "item_description": "Moister Analyzer sampling Pan", "item_quantity": "02", "item_uom": "Boxes"},
            {"item_no": "RT24-32", "item_description": "Normal Saline", "item_quantity": "25", "item_uom": "Ampoules"},
            {"item_no": "RT24-33", "item_description": "Water for Injection (WFI)", "item_quantity": "100", "item_uom": "Ampoules"},
            {"item_no": "RT24-34", "item_description": "Karl Fischer Reagent", "item_quantity": "01", "item_uom": "Set"},
            {"item_no": "RT24-35", "item_description": "Tetanus anti-toxin (Equine Origin) for LF Test", "item_quantity": "10", "item_uom": "Ampoules / Vials"},
            {"item_no": "RT24-36", "item_description": "Standard tetanus toxoid for LF test", "item_quantity": "05", "item_uom": "Ampoules / Vials"},
            {"item_no": "RT24-37", "item_description": "Anti-Diphtheria Serum for flocculation test", "item_quantity": "05", "item_uom": "Ampoules / Vials"},
            {"item_no": "RT24-38", "item_description": "Standard diphtheria toxoid for LF test", "item_quantity": "05", "item_uom": "Ampoules / Vials"},
            {"item_no": "RT24-39", "item_description": "10X Eagle's MEM (Minimum essential medium)", "item_quantity": "02", "item_uom": "Bottles"},
            {"item_no": "RT24-40", "item_description": "Fetal Bovine Serum", "item_quantity": "02", "item_uom": "Bottles"},
            {"item_no": "RT24-41", "item_description": "L-Glutamine", "item_quantity": "02", "item_uom": "Bottles"},
            {"item_no": "RT24-42", "item_description": "Amphotericin-B", "item_quantity": "02", "item_uom": "Bottles"},
            {"item_no": "RT24-43", "item_description": "Penicillin-Streptomycin", "item_quantity": "02", "item_uom": "Bottles"},
            {"item_no": "RT24-44", "item_description": "Non-Essential Amino-Acids (100X) for MEM", "item_quantity": "02", "item_uom": "Bottles"},
            {"item_no": "RT24-45", "item_description": "Phenol Red", "item_quantity": "02", "item_uom": "Bottles"},
            {"item_no": "RT24-46", "item_description": "Fungizone", "item_quantity": "02", "item_uom": "Bottles"},
            {"item_no": "RT24-47", "item_description": "Trypsin 1X", "item_quantity": "02", "item_uom": "Bottles"},
            {"item_no": "RT24-48", "item_description": "Anti-Polio Antisera (Antibodies type 1)", "item_quantity": "01", "item_uom": "Ampoule / Vial"},
            {"item_no": "RT24-49", "item_description": "Anti-Polio Antisera (Antibodies type 2)", "item_quantity": "01", "item_uom": "Ampoule / Vial"},
            {"item_no": "RT24-50", "item_description": "Anti-Polio Antisera (Antibodies type 3)", "item_quantity": "01", "item_uom": "Ampoule / Vial"},
            {"item_no": "RT24-51", "item_description": "Sterile 96 wells flat-bottom micro-titration plates for cell culture", "item_quantity": "100", "item_uom": "Plates"},
            {"item_no": "RT24-52", "item_description": "HEPES buffer", "item_quantity": "02", "item_uom": "Bottles"},
            {"item_no": "RT24-53", "item_description": "Disposable Pipettes (1ml-5ml)", "item_quantity": "200", "item_uom": "Units"},
            {"item_no": "RT24-54", "item_description": "Disposable Pipettes (1ml-10ml)", "item_quantity": "100", "item_uom": "Units"},
            {"item_no": "RT24-55", "item_description": "Tissue Paper", "item_quantity": "10", "item_uom": "Boxes"},
            {"item_no": "RT24-56", "item_description": "Trypan Blue", "item_quantity": "02", "item_uom": "Bottles"},
            {"item_no": "RT24-57", "item_description": "Acetone (Lab Grade)", "item_quantity": "05", "item_uom": "Bottles"},
            {"item_no": "RT24-58", "item_description": "Chloroform (Lab Grade)", "item_quantity": "05", "item_uom": "Bottles"},
            {"item_no": "RT24-59", "item_description": "1-Pyridyl-2-Azonaphthol (PAN) Indicator", "item_quantity": "02", "item_uom": "Bottles"},
            {"item_no": "RT24-60", "item_description": "Aluminum phosphate gel (Pure)", "item_quantity": "05", "item_uom": "Bottles"},
            {"item_no": "RT24-61", "item_description": "Absolute ethanol", "item_quantity": "05", "item_uom": "Bottles"},
            {"item_no": "RT24-62", "item_description": "Copper sulphate pentahydrate", "item_quantity": "02", "item_uom": "Bottles"},
            {"item_no": "RT24-63", "item_description": "Disodium Edetate", "item_quantity": "02", "item_uom": "Bottles"},
            {"item_no": "RT24-64", "item_description": "Burette", "item_quantity": "06", "item_uom": "Units"},
            {"item_no": "RT24-65", "item_description": "Burette Stand", "item_quantity": "03", "item_uom": "Units"},
            {"item_no": "RT24-66", "item_description": "Quartz cuvettes", "item_quantity": "06", "item_uom": "Units"},
            {"item_no": "RT24-67", "item_description": "Amber colored volumetric flask", "item_quantity": "12", "item_uom": "Units"},
        ],
    },
    {
        "source_name": "official_drap_page_and_pdf",
        "title": "Tender notice for supply of Fourier Transform Infrared Spectrophotometer (FTIR) to CDL Karachi",
        "publication_date": "2024-05-31",
        "closing_date": "2024-06-17",
        "buyer": "Central Drugs Laboratory, Drug Regulatory Authority of Pakistan",
        "contract_period": "FY 2023-24",
        "classification": "healthcare tender document",
        "status": "published",
        "notice_id": "tender-notice-for-supply-of-fourier-transform-infrared-spectrophotometer-ftir-to-cdl-karachi",
        "notice_url": "https://www.dra.gov.pk/news_updates/tenders/tender-notice-for-supply-of-fourier-transform-infrared-spectrophotometer-ftir-to-cdl-karachi/",
        "description": "Supply of Fourier Transform Infrared Spectrophotometer (FTIR) to Central Drugs Laboratory Karachi during FY 2023-24.",
        "query_text": "ftir, spectrophotometer, laboratory, medical, healthcare, cdl karachi",
        "items": [
            {
                "item_no": "FTIR-01",
                "item_description": "Fourier Transform Infrared Spectrophotometer (FTIR)",
                "item_quantity": "01",
                "item_uom": "unit",
            },
        ],
    },
    {
        "source_name": "official_drap_page_and_pdf",
        "title": "Invitation to bid (For the supply of chemicals, glassware, reference standards/USP standards/CRMs and columns)",
        "publication_date": "2026-03-25",
        "closing_date": "2026-04-09",
        "buyer": "Central Drugs Laboratory, Drug Regulatory Authority of Pakistan",
        "contract_period": "FY 2025-26",
        "classification": "healthcare tender document",
        "status": "published",
        "notice_id": "invitation-to-bid-for-the-supply-of-chemicals-glassware-reference-standards-usp-standards-crms-and-columns",
        "notice_url": "https://www.dra.gov.pk/news_updates/tenders/invitation-to-bid-for-the-supply-of-chemicals-glassware-reference-standards-usp-standards-crms-and-columns/",
        "description": "Supply of chemicals, glassware, reference standards, USP standards, CRMs, and columns to Central Drugs Laboratory Karachi during FY 2025-26.",
        "query_text": "chemicals, glassware, reference standards, usp standards, crms, columns, laboratory, medical, healthcare",
        "items": [
            {
                "item_no": "CDL26-01",
                "item_description": "Chemicals, glassware, reference standards, USP standards, CRMs, and columns for Central Drugs Laboratory Karachi",
                "item_quantity": "01",
                "item_uom": "tender package",
            },
        ],
    },
    {
        "source_name": "official_drap_page_and_pdf",
        "title": "Tender for supply of lab equipment",
        "publication_date": "2025-01-16",
        "closing_date": "2025-01-31",
        "buyer": "Central Drugs Laboratory, Drug Regulatory Authority of Pakistan",
        "contract_period": "FY 2024-25",
        "currency": "PKR",
        "amount": "2575000",
        "notice_id": "tender-for-supply-of-lab-equipment",
        "notice_url": "https://www.dra.gov.pk/news_updates/tenders/tender-for-supply-of-lab-equipment/",
        "description": "Supply of laboratory equipment for Central Drugs Laboratory, DRAP Karachi during FY 2024-25.",
        "query_text": "lab, laboratory, equipment, medical, healthcare",
        "items": [
            {
                "item_no": "1",
                "item_description": "HPLC with PDA Detector",
                "item_quantity": "01",
                "item_uom": "unit",
                "item_unit_price": "500000",
            },
            {
                "item_no": "2",
                "item_description": "Microbalance",
                "item_quantity": "02",
                "item_uom": "units",
                "item_unit_price": "350000",
            },
            {
                "item_no": "3",
                "item_description": "Next Generation Impactor + Dose Uniformity Sampling Apparatus",
                "item_quantity": "01",
                "item_uom": "unit",
                "item_unit_price": "750000",
            },
            {
                "item_no": "4",
                "item_description": "Thermal Gravimetric Analyzer",
                "item_quantity": "01",
                "item_uom": "unit",
                "item_unit_price": "500000",
            },
            {"item_no": "5", "item_description": "Oven", "item_quantity": "01", "item_uom": "unit", "item_unit_price": "150000"},
            {"item_no": "6", "item_description": "Hot Incubator", "item_quantity": "01", "item_uom": "unit", "item_unit_price": "200000"},
            {
                "item_no": "7",
                "item_description": "pH meter with printers",
                "item_quantity": "02",
                "item_uom": "units",
                "item_unit_price": "50000",
            },
            {
                "item_no": "8",
                "item_description": "Laboratory Refrigerator",
                "item_quantity": "01",
                "item_uom": "unit",
                "item_unit_price": "75000",
            },
        ],
    },
    {
        "source_name": "official_drap_page_and_pdf",
        "title": "Invitation to bid for Supply of Chemicals, reagents, reference standard, glassware and kits",
        "publication_date": "2025-09-05",
        "closing_date": "2025-09-24",
        "buyer": "National Control Laboratory for Biologicals, Drug Regulatory Authority of Pakistan",
        "contract_period": "FY 2025-26",
        "notice_id": "invitation-to-bid-for-supply-of-chemicals-reagents-reference-standard-glassware-and-kits",
        "notice_url": "https://www.dra.gov.pk/news_updates/tenders/invitation-to-bid-for-supply-of-chemicals-reagents-reference-standard-glassware-and-kits/",
        "description": "Supply of chemicals, reagents, reference standards, glassware and kits for NCLB, DRAP Islamabad during FY 2025-26.",
        "query_text": "chemical, reagent, reference standard, glassware, kit, laboratory, medical, healthcare",
        "items": [
            {"item_no": "Lot1-01", "item_description": "Aluminum hydroxide Gel", "item_quantity": "01", "item_uom": "01kg"},
            {"item_no": "Lot1-02", "item_description": "Disodium edentate", "item_quantity": "01", "item_uom": "01kg"},
            {"item_no": "Lot1-03", "item_description": "Physiological Saline", "item_quantity": "02", "item_uom": "05 L"},
            {"item_no": "Lot1-04", "item_description": "Ammonium acetate", "item_quantity": "01", "item_uom": "01kg"},
            {"item_no": "Lot1-05", "item_description": "Thiomersal", "item_quantity": "01", "item_uom": "500gm"},
            {"item_no": "Lot1-06", "item_description": "Milli Q/ reagent water", "item_quantity": "04", "item_uom": "2.5L"},
            {"item_no": "Lot2-01", "item_description": "Absolute Ethanol", "item_quantity": "01", "item_uom": "2.5L"},
            {"item_no": "Lot2-02", "item_description": "70 % Iso-propyl alcohol", "item_quantity": "10", "item_uom": "2.5L"},
            {"item_no": "Lot2-03", "item_description": "Rectified Spirit", "item_quantity": "10", "item_uom": "2.5L"},
            {"item_no": "Lot2-04", "item_description": "70% ethanol", "item_quantity": "02", "item_uom": "2.5L"},
            {"item_no": "Lot2-05", "item_description": "Water for Injection (WFI)", "item_quantity": "20", "item_uom": "10ml"},
            {"item_no": "Lot2-06", "item_description": "Purified/ distilled water", "item_quantity": "30", "item_uom": "5L"},
            {"item_no": "Lot3-01", "item_description": "Conc. Sulphuric acid", "item_quantity": "01", "item_uom": "2.5L"},
            {"item_no": "Lot3-02", "item_description": "Conc. Nitric acid", "item_quantity": "01", "item_uom": "2.5L"},
            {"item_no": "Lot4-01", "item_description": "Acetic Acid-HPLC Grade", "item_quantity": "01", "item_uom": "2.5L"},
            {"item_no": "Lot4-02", "item_description": "Agarose powder", "item_quantity": "01", "item_uom": "500g"},
            {"item_no": "Lot4-03", "item_description": "Boric acid", "item_quantity": "01", "item_uom": "500 g"},
            {"item_no": "Lot4-04", "item_description": "EDTA", "item_quantity": "01", "item_uom": "01 kg"},
            {"item_no": "Lot4-05", "item_description": "Glycerol", "item_quantity": "01", "item_uom": "2.5L"},
            {"item_no": "Lot4-06", "item_description": "Lithium hydroxide", "item_quantity": "01", "item_uom": "500g"},
            {"item_no": "Lot4-07", "item_description": "Toluidine blue", "item_quantity": "01", "item_uom": "100g"},
            {"item_no": "Lot4-08", "item_description": "Tris base", "item_quantity": "01", "item_uom": "500g"},
            {"item_no": "Lot4-09", "item_description": "Trisma base", "item_quantity": "01", "item_uom": "500g"},
            {
                "item_no": "Lot4-10",
                "item_description": "Sodium Chloride (Pure, Lab Grade)",
                "item_quantity": "02",
                "item_uom": "01kg",
            },
            {
                "item_no": "Lot4-11",
                "item_description": "Potassium dihydrogen phosphate",
                "item_quantity": "01",
                "item_uom": "01kg",
            },
            {
                "item_no": "Lot4-12",
                "item_description": "Dipotassium hydrogen phosphate",
                "item_quantity": "01",
                "item_uom": "01kg",
            },
            {"item_no": "Lot5-01", "item_description": "Peptone water", "item_quantity": "01", "item_uom": "500g"},
            {
                "item_no": "Lot5-02",
                "item_description": "FTM (fluid thioglycolate medium)",
                "item_quantity": "01",
                "item_uom": "500g",
            },
            {
                "item_no": "Lot5-03",
                "item_description": "TSB (Tryptic Soya Broth) medium",
                "item_quantity": "01",
                "item_uom": "500g",
            },
            {"item_no": "Lot5-04", "item_description": "Bovine Serum Albumin", "item_quantity": "02", "item_uom": "100g"},
            {"item_no": "Lot5-05", "item_description": "pH buffer (pH 4)", "item_quantity": "01", "item_uom": "500ml"},
            {"item_no": "Lot5-06", "item_description": "pH buffer (pH 7)", "item_quantity": "01", "item_uom": "500ml"},
            {"item_no": "Lot5-07", "item_description": "pH buffer (pH 10)", "item_quantity": "01", "item_uom": "500ml"},
            {
                "item_no": "Lot5-08",
                "item_description": "KCl solution 3M (preservative for pH probe)",
                "item_quantity": "01",
                "item_uom": "100ml",
            },
            {"item_no": "Lot6-01", "item_description": "Diethanolamine", "item_quantity": "02", "item_uom": "01L"},
            {"item_no": "Lot6-02", "item_description": "Triton X-100", "item_quantity": "01", "item_uom": "500ml"},
            {
                "item_no": "Lot8-01",
                "item_description": "Vial decapper set (8mm, 11mm, 13mm, 20mm and 30mm stainless steel variants)",
                "item_quantity": "06",
                "item_uom": "units",
            },
            {
                "item_no": "Lot8-02",
                "item_description": "Ampoule Cutter (stainless steel, multi-size 0.5ml to 10ml ampoules)",
                "item_quantity": "05",
                "item_uom": "units",
            },
            {
                "item_no": "Lot9-01",
                "item_description": "Heparin Sodium BRP Reference standard (H0200000)",
                "item_quantity": "05",
                "item_uom": "01 ml unit",
            },
            {
                "item_no": "Lot10-01",
                "item_description": "Osmometer standards (50, 850, 280 mOsm/kg)",
                "item_quantity": "03",
                "item_uom": "standards",
            },
            {
                "item_no": "Lot11-01",
                "item_description": "Tetanus toxoid potency reference standard, 4th WHO international standard for tetanus toxoid adsorbed (NIBSC 08/218)",
                "item_quantity": "02",
                "item_uom": "ampoules",
            },
            {
                "item_no": "Lot11-02",
                "item_description": "3rd International standard toxoid for flocculation test (NIBSC 16/302)",
                "item_quantity": "02",
                "item_uom": "ampoules",
            },
            {
                "item_no": "Lot11-03",
                "item_description": "1st WHO reference reagent tetanus anti-toxin equine for flocculation test (NIBSC 21/230)",
                "item_quantity": "02",
                "item_uom": "ampoules",
            },
            {
                "item_no": "Lot12-01",
                "item_description": "Staphylococcus aureus - ATCC 6538",
                "item_quantity": "01",
                "item_uom": "pack (10 pellet)",
            },
            {
                "item_no": "Lot12-02",
                "item_description": "Escherichia coli - ATCC 8739",
                "item_quantity": "01",
                "item_uom": "pack (10 pellet)",
            },
            {
                "item_no": "Lot12-03",
                "item_description": "Pseudomonas aeruginosa - ATCC 9027",
                "item_quantity": "01",
                "item_uom": "pack (10 pellet)",
            },
            {
                "item_no": "Lot12-04",
                "item_description": "Candida albicans - ATCC 10231",
                "item_quantity": "01",
                "item_uom": "pack (06 pellet)",
            },
            {
                "item_no": "Lot12-05",
                "item_description": "Aspergillus brasiliensis (formerly A. niger) - ATCC 16404",
                "item_quantity": "01",
                "item_uom": "pack (06 pellet)",
            },
            {
                "item_no": "Lot13-01",
                "item_description": "Anti-factor IIa kit (heparin product testing), 5-test EP-UFH anti-IIa starter set or compatible",
                "item_quantity": "02",
                "item_uom": "kits",
            },
            {
                "item_no": "Lot14-01",
                "item_description": "Hepatitis B surface antigen reagent kit with positive and negative controls (HBs Ag ELISA)",
                "item_quantity": "10",
                "item_uom": "kits",
            },
            {
                "item_no": "Lot15-01",
                "item_description": "BET Kit (lysate 0.25EU/ml) with LAL water, endotoxin free or <0.005 EU/ml",
                "item_quantity": "05",
                "item_uom": "kits",
            },
            {
                "item_no": "Lot16-01",
                "item_description": "Osmometer sampler tips for Advanced Instrument model 3320",
                "item_quantity": "01",
                "item_uom": "box (500 tips)",
            },
            {
                "item_no": "Lot17-01",
                "item_description": "Burette, 50ml, Type 1 borosilicate glass with stopper",
                "item_quantity": "05",
                "item_uom": "units",
            },
            {
                "item_no": "Lot17-02",
                "item_description": "Burette Stand, metal, suitable for 50 ml burette",
                "item_quantity": "03",
                "item_uom": "units",
            },
            {
                "item_no": "Lot17-03",
                "item_description": "Quartz cuvettes, UV/VIS/NIR, 3.5 ml transmitting quartz cuvettes with stoppers",
                "item_quantity": "05",
                "item_uom": "units",
            },
            {
                "item_no": "Lot17-04",
                "item_description": "Amber colored volumetric flask, 200 ml, Type-1 borosilicate glass",
                "item_quantity": "10",
                "item_uom": "units",
            },
        ],
    },
    {
        "source_name": "official_drap_page_and_pdf",
        "title": "Prequalification of companies/ firms/ suppliers for supply of chemicals and glassware etc. to CDL Karachi",
        "publication_date": "2024-02-23",
        "closing_date": "2024-03-08",
        "buyer": "Central Drugs Laboratory, Drug Regulatory Authority of Pakistan",
        "contract_period": "Three-year framework agreement",
        "classification": "healthcare prequalification document",
        "status": "published",
        "notice_id": "prequalification-of-companies-firms-suppliers-for-supply-of-chemicals-and-glassware-etc-to-cdl-karachi",
        "notice_url": "https://www.dra.gov.pk/news_updates/tenders/prequalification-of-companies-firms-suppliers-for-supply-of-chemicals-and-glassware-etc-to-cdl-karachi/",
        "description": "Prequalification and indicative schedule of requirements for supply of chemicals and glassware to CDL Karachi through framework agreement.",
        "query_text": "chemical, glassware, laboratory, cdl karachi, medical, healthcare",
        "items": [
            {"item_no": "Chem-001", "item_description": "Perchloric Acid", "item_quantity": "04", "item_uom": "litre"},
            {"item_no": "Chem-002", "item_description": "Acetonitrile HPLC", "item_quantity": "2000", "item_uom": "x 2.5 litres"},
            {"item_no": "Chem-003", "item_description": "Buffer pH 10", "item_quantity": "40", "item_uom": "x1 litre"},
            {"item_no": "Chem-004", "item_description": "Buffer pH 4", "item_quantity": "40", "item_uom": "x1 litre"},
            {"item_no": "Chem-018", "item_description": "Reagent Bottles 1000ml", "item_quantity": "400", "item_uom": "Nos"},
            {"item_no": "Chem-019", "item_description": "Sodium-1-Heptane Sulphonate", "item_quantity": "80", "item_uom": "x50g"},
            {"item_no": "Chem-020", "item_description": "Sodium-1-Pentane Sulphonate", "item_quantity": "80", "item_uom": "x50g"},
            {"item_no": "Chem-021", "item_description": "Sodium 1-hexane sulphonate", "item_quantity": "80", "item_uom": "x50g"},
            {"item_no": "Chem-022", "item_description": "Sodium hydroxide", "item_quantity": "200", "item_uom": "x1 Kg"},
            {"item_no": "Chem-023", "item_description": "Sodium octane sulphonate", "item_quantity": "20", "item_uom": "x50g"},
            {"item_no": "Chem-024", "item_description": "Pyridine", "item_quantity": "4", "item_uom": "x1 liter"},
            {"item_no": "Chem-025", "item_description": "Chloroform", "item_quantity": "40", "item_uom": "x2.5 litre"},
            {"item_no": "Chem-026", "item_description": "Tetrahydrofuran", "item_quantity": "12", "item_uom": "x2.5 litre"},
            {"item_no": "Chem-027", "item_description": "4-Amino Phenol", "item_quantity": "4", "item_uom": "x50g"},
            {"item_no": "Chem-028", "item_description": "Acetone", "item_quantity": "4", "item_uom": "x2.5 liter"},
            {"item_no": "Chem-029", "item_description": "Aerosol", "item_quantity": "8", "item_uom": "x50g"},
            {"item_no": "Chem-030", "item_description": "Ammonia Solution", "item_quantity": "12", "item_uom": "x2.5 liter"},
            {"item_no": "Chem-031", "item_description": "Ammonium Acetate", "item_quantity": "20", "item_uom": "x1kg"},
            {"item_no": "Chem-032", "item_description": "Ammonium bicarbonate", "item_quantity": "4", "item_uom": "x1kg"},
            {"item_no": "Chem-033", "item_description": "Ammonium Cerium", "item_quantity": "4", "item_uom": "x50g"},
            {"item_no": "Chem-034", "item_description": "Ammonium Chloride", "item_quantity": "4", "item_uom": "x1kg"},
            {"item_no": "Chem-035", "item_description": "Ammonium dihydrogen Phosphate", "item_quantity": "8", "item_uom": "x1kg"},
            {"item_no": "Chem-036", "item_description": "Ammonium dihydrogen Phosphate Anhydrous", "item_quantity": "12", "item_uom": "x1 Kg"},
            {"item_no": "Chem-037", "item_description": "Ammonium Formate", "item_quantity": "4", "item_uom": "x50g"},
            {"item_no": "Chem-038", "item_description": "Ammonium Hydroxide", "item_quantity": "8", "item_uom": "x1kg"},
            {"item_no": "Chem-039", "item_description": "Ammonium Iron (III) Sulphate", "item_quantity": "8", "item_uom": "x1kg"},
            {"item_no": "Chem-040", "item_description": "Dodea Hydrate", "item_quantity": "4", "item_uom": "x1Kg"},
            {"item_no": "Chem-041", "item_description": "Ammonium Iron Sulphate", "item_quantity": "4", "item_uom": "x500g"},
            {"item_no": "Chem-042", "item_description": "Ammonium Metavanadate", "item_quantity": "4", "item_uom": "x100g"},
            {"item_no": "Chem-043", "item_description": "Ammonium Molybdate", "item_quantity": "4", "item_uom": "x1kg"},
            {"item_no": "Chem-044", "item_description": "Ammonium Monovanadate", "item_quantity": "4", "item_uom": "x100g"},
            {"item_no": "Chem-045", "item_description": "Ammonium Nitrate", "item_quantity": "4", "item_uom": "x500g"},
            {"item_no": "Chem-046", "item_description": "Ammonium Oxalate", "item_quantity": "4", "item_uom": "x1000g"},
            {"item_no": "Chem-047", "item_description": "Ammonium Phosphate Diabasic", "item_quantity": "20", "item_uom": "x1kg"},
            {"item_no": "Chem-048", "item_description": "Ammonium Phosphate Monobasic", "item_quantity": "20", "item_uom": "x1kg"},
            {"item_no": "Chem-049", "item_description": "Ammonium Potassium Sulphate", "item_quantity": "20", "item_uom": "x1kg"},
            {"item_no": "Chem-050", "item_description": "Ammonium Thiocyanate", "item_quantity": "4", "item_uom": "x1kg"},
            {"item_no": "Chem-051", "item_description": "Acetic Acid Anhydrous", "item_quantity": "24", "item_uom": "x1Kg"},
            {"item_no": "Chem-052", "item_description": "Anthracena", "item_quantity": "4", "item_uom": "x100g"},
            {"item_no": "Chem-053", "item_description": "Acetic Acid Anhydrous", "item_quantity": "48", "item_uom": "x 2 1/2 liter"},
            {"item_no": "Chem-054", "item_description": "Anthracena", "item_quantity": "4", "item_uom": "x100g"},
            {"item_no": "Chem-055", "item_description": "Acetonitrile HPLC", "item_quantity": "2000", "item_uom": "x 2 1/2"},
            {"item_no": "Chem-056", "item_description": "Benzophenon", "item_quantity": "4", "item_uom": "x800gm"},
            {"item_no": "Chem-057", "item_description": "2.2 Biphyridina", "item_quantity": "4", "item_uom": "x25 gm"},
            {"item_no": "Chem-058", "item_description": "Boric acid", "item_quantity": "4", "item_uom": "x1 kg"},
            {"item_no": "Chem-059", "item_description": "Brig - 35", "item_quantity": "8", "item_uom": "x500 gm"},
            {"item_no": "Chem-060", "item_description": "Buffer pH.4", "item_quantity": "40", "item_uom": "x1 liter"},
            {"item_no": "Chem-061", "item_description": "Buffer pH-7", "item_quantity": "40", "item_uom": "x1 liter"},
            {"item_no": "Chem-062", "item_description": "Buffer pH-10", "item_quantity": "40", "item_uom": "x1 liter"},
            {"item_no": "Chem-063", "item_description": "Buffer pH-2", "item_quantity": "", "item_uom": ""},
            {"item_no": "Chem-064", "item_description": "Carbzaole", "item_quantity": "4", "item_uom": "x100gm"},
            {"item_no": "Chem-065", "item_description": "Carbon Disulphate", "item_quantity": "4", "item_uom": "x1liter"},
            {"item_no": "Chem-066", "item_description": "Chlorobuton", "item_quantity": "4", "item_uom": "x1liter"},
            {"item_no": "Chem-067", "item_description": "Chloroform", "item_quantity": "24", "item_uom": "x 2/1/2 liter"},
            {"item_no": "Chem-068", "item_description": "Citric Acid Monohydrate", "item_quantity": "4", "item_uom": "x1Kg"},
            {"item_no": "Chem-069", "item_description": "Concentrated HCl", "item_quantity": "4", "item_uom": "x2.5 liter"},
            {"item_no": "Chem-070", "item_description": "Copper Sulphate", "item_quantity": "4", "item_uom": "x1 kg"},
            {"item_no": "Chem-071", "item_description": "Di-Ammonia Hydrogen Citrate", "item_quantity": "4", "item_uom": "x1 kg"},
            {"item_no": "Chem-072", "item_description": "Di phenylamine (liquid)", "item_quantity": "4", "item_uom": "x100ml"},
            {"item_no": "Chem-073", "item_description": "Diphenylanin Solid", "item_quantity": "4", "item_uom": "x100gm"},
            {"item_no": "Chem-074", "item_description": "Di Sodium Edetate", "item_quantity": "4", "item_uom": "x1 kg"},
            {"item_no": "Chem-075", "item_description": "Di Sodium Hyrogen Phosphate dudeca Hydrate", "item_quantity": "4", "item_uom": "x1 kg"},
            {"item_no": "Chem-076", "item_description": "Dibasic Sodium Phosphate", "item_quantity": "4", "item_uom": "x1 kg"},
            {"item_no": "Chem-077", "item_description": "Dihydroxy 1-3 Benzon Di Acid", "item_quantity": "8", "item_uom": "x5gm"},
            {"item_no": "Chem-078", "item_description": "Endotoxin Kit 0.25 sensitivity", "item_quantity": "80", "item_uom": "Kits"},
            {"item_no": "Chem-079", "item_description": "Media 1", "item_quantity": "24", "item_uom": "Bottle"},
            {"item_no": "Chem-080", "item_description": "Media 10", "item_quantity": "08", "item_uom": "Bottle"},
            {"item_no": "Chem-081", "item_description": "Media 11", "item_quantity": "16", "item_uom": "Bottle"},
            {"item_no": "Chem-096", "item_description": "Micrococcus Luteus ATCC9341", "item_quantity": "08", "item_uom": "vials"},
            {"item_no": "Chem-097", "item_description": "Brodetella Bronchiseptia ACC10536", "item_quantity": "08", "item_uom": "vials"},
            {"item_no": "Chem-098", "item_description": "Staphylococcus Aureus ATCC6538", "item_quantity": "08", "item_uom": "vials"},
            {"item_no": "Chem-099", "item_description": "Bacillus Stero thermophillis", "item_quantity": "08", "item_uom": "vials"},
            {"item_no": "Chem-100", "item_description": "Chemical Indicator for Sterilizer / Autoclave", "item_quantity": "20", "item_uom": "Packs"},
            {"item_no": "Chem-101", "item_description": "Biological Indicators", "item_quantity": "20", "item_uom": "Packs"},
            {"item_no": "Chem-102", "item_description": "Water for injection", "item_quantity": "40", "item_uom": "packs"},
            {"item_no": "Chem-103", "item_description": "Helium gas 2000 bar", "item_quantity": "12", "item_uom": "cylinders"},
            {"item_no": "Chem-104", "item_description": "Hydrogen gas 2000 bar", "item_quantity": "12", "item_uom": "cylinders"},
            {"item_no": "Chem-105", "item_description": "Nitrogen gas 2000 bar", "item_quantity": "4", "item_uom": "cylinders"},
            {"item_no": "Chem-106", "item_description": "Acetylene gas 2000 bar", "item_quantity": "6", "item_uom": "cylinders"},
            {"item_no": "Chem-107", "item_description": "Argan gas 2000 bar", "item_quantity": "4", "item_uom": "cylinders"},
            {"item_no": "Glass-001", "item_description": "Volumetric Flask 10ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-002", "item_description": "Volumetric Flask 25ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-003", "item_description": "Volumetric Flask 50ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-004", "item_description": "Volumetric Flask 100ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-005", "item_description": "Volumetric Flask 200ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-006", "item_description": "Volumetric Flask with Stopper 10ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-007", "item_description": "Volumetric Flask with Stopper 25ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-008", "item_description": "Volumetric Flask with Stopper 50ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-009", "item_description": "Volumetric Flask with Stopper 100ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-010", "item_description": "Volumetric Flask with Stopper 200ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-011", "item_description": "Volumetric Pipette 1ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-012", "item_description": "Volumetric Pipette 2ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-013", "item_description": "Volumetric Pipette 5ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-014", "item_description": "Volumetric Pipette 10ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-015", "item_description": "Volumetric Pipette 20ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-016", "item_description": "Volumetric Pipette 25ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-017", "item_description": "Measuring Pipette 2ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-018", "item_description": "Measuring Pipette 5ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-019", "item_description": "Measuring Pipette 10ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-020", "item_description": "Measuring Pipette 20ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-021", "item_description": "Measuring Pipette 25ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-022", "item_description": "Measuring Cylinder 5ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-023", "item_description": "Measuring Cylinder 10ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-024", "item_description": "Measuring Cylinder 25ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-025", "item_description": "Measuring Cylinder 50ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-026", "item_description": "Measuring Cylinder 100ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-027", "item_description": "Measuring Cylinder 250ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-028", "item_description": "Measuring Cylinder 500ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-029", "item_description": "Measuring Cylinder 1000ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-030", "item_description": "Measuring Cylinder with stopper 5ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-031", "item_description": "Measuring Cylinder with stopper 10ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-032", "item_description": "Measuring Cylinder with stopper 25ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-033", "item_description": "Measuring Cylinder with stopper 50ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-034", "item_description": "Measuring Cylinder with stopper 100ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-035", "item_description": "Measuring Cylinder with stopper 250ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-036", "item_description": "Measuring Cylinder with stopper 500ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-037", "item_description": "Measuring Cylinder with stopper 1000ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-038", "item_description": "Beaker Glass 25ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-039", "item_description": "Beaker Glass 50ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-040", "item_description": "Beaker Glass 100ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-041", "item_description": "Beaker Glass 250ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-042", "item_description": "Beaker Glass 500ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-043", "item_description": "Beaker Glass 1000ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-044", "item_description": "Beaker Glass 2000ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-045", "item_description": "Beaker Plastic 1000ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-046", "item_description": "Beaker Plastic 2000ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-047", "item_description": "Pippette Sucker Digital with micro measruing", "item_quantity": "24", "item_uom": "Nos"},
            {"item_no": "Glass-048", "item_description": "Pippette Sucker Digital with macro measruing", "item_quantity": "24", "item_uom": "Nos"},
            {"item_no": "Glass-049", "item_description": "Reagent Bottle for HPLC with Cape 250ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-050", "item_description": "Reagent Bottle for HPLC with Cape 500ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-051", "item_description": "Reagent Bottle for HPLC with Cape 1000ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-052", "item_description": "Reagent Bottle for HPLC with Cape 2000ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-053", "item_description": "Nylon Filter", "item_quantity": "100", "item_uom": "x1500 Boxes"},
            {"item_no": "Glass-054", "item_description": "Filter Paper 0.45mm", "item_quantity": "100", "item_uom": "x1000 Boxes"},
            {"item_no": "Glass-055", "item_description": "Filter Paper Whattman (Small)", "item_quantity": "100", "item_uom": "x1000 Boxes"},
            {"item_no": "Glass-056", "item_description": "Filter Paper 2'x3' (Large)", "item_quantity": "100", "item_uom": "x1500 Reams"},
            {"item_no": "Glass-057", "item_description": "Test Tube with stopper 25ml", "item_quantity": "100", "item_uom": "x10 Boxes"},
            {"item_no": "Glass-058", "item_description": "Test Tube without stopper 25ml", "item_quantity": "100", "item_uom": "x10 Boxes"},
            {"item_no": "Glass-059", "item_description": "Gravity Thermometer 25ml", "item_quantity": "25", "item_uom": "Nos"},
            {"item_no": "Glass-060", "item_description": "Motel Piston 500ml", "item_quantity": "50", "item_uom": "Nos"},
            {"item_no": "Glass-061", "item_description": "Motel Piston 1000ml", "item_quantity": "50", "item_uom": "Nos"},
            {"item_no": "Glass-062", "item_description": "Conical Flask 25ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-063", "item_description": "Conical Flask 50ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-064", "item_description": "Conical Flask 100ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-065", "item_description": "Conical Flask 250ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-066", "item_description": "Conical Flask 500ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-067", "item_description": "Conical Flask 1000ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-068", "item_description": "Conical Flask 2000ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-069", "item_description": "Filteration Chamber Complete Set with Flask", "item_quantity": "25", "item_uom": "Nos"},
            {"item_no": "Glass-070", "item_description": "Test Tube 10ml", "item_quantity": "500", "item_uom": "Packet"},
            {"item_no": "Glass-071", "item_description": "Test Tube Stand", "item_quantity": "10", "item_uom": "Nos"},
            {"item_no": "Glass-072", "item_description": "China Dish (Ceramic)", "item_quantity": "24", "item_uom": "Nos"},
            {"item_no": "Glass-073", "item_description": "China Dish with Cover", "item_quantity": "24", "item_uom": "Nos"},
            {"item_no": "Glass-074", "item_description": "Flat Bottom Flask 2000ml", "item_quantity": "24", "item_uom": "Nos"},
            {"item_no": "Glass-075", "item_description": "Flat Bottom Flask with stopper 1000ml", "item_quantity": "24", "item_uom": "Nos"},
            {"item_no": "Glass-076", "item_description": "Flat Bottom Flask with stopper 2000ml", "item_quantity": "24", "item_uom": "Nos"},
            {"item_no": "Glass-077", "item_description": "Glass Funnel 250ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-078", "item_description": "Glass Funnel 50ml", "item_quantity": "200", "item_uom": "Nos"},
            {"item_no": "Glass-079", "item_description": "Burette 5ml", "item_quantity": "25", "item_uom": "Nos"},
            {"item_no": "Glass-080", "item_description": "Burette 25ml", "item_quantity": "25", "item_uom": "Nos"},
            {"item_no": "Glass-081", "item_description": "Washing Bottle 1000ml", "item_quantity": "25", "item_uom": "Nos"},
            {"item_no": "Glass-082", "item_description": "Pippette Sucker", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-083", "item_description": "Pippette volumetric 1ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-084", "item_description": "Pippette volumetric 2ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-085", "item_description": "Pippette volumetric 5ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-086", "item_description": "Pippette volumetric 10ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-087", "item_description": "Pippette volumetric 20ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-088", "item_description": "Pippette volumetric 25ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-089", "item_description": "Pippette measuring 1ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-090", "item_description": "Pippette measuring 2ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-091", "item_description": "Pippette measuring 5ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-092", "item_description": "Pippette measuring 10ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-093", "item_description": "Pippette measuring 20ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-094", "item_description": "Pippette measuring 25ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-095", "item_description": "Glass Bottle 5ml with Plastic Cape", "item_quantity": "50", "item_uom": "Packets"},
            {"item_no": "Glass-096", "item_description": "Media Bottles 250ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-097", "item_description": "Media Bottles 500ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-098", "item_description": "Media Bottles 1000ml", "item_quantity": "100", "item_uom": "Nos"},
            {"item_no": "Glass-099", "item_description": "Media Bottles 2000ml", "item_quantity": "24", "item_uom": "Nos"},
            {"item_no": "Glass-100", "item_description": "Butter Paper", "item_quantity": "80", "item_uom": "Packs"},
            {"item_no": "Glass-101", "item_description": "Micro Pippette 1-100 micro liter", "item_quantity": "08", "item_uom": "Nos"},
            {"item_no": "Glass-102", "item_description": "Micro Pippette 1ml", "item_quantity": "08", "item_uom": "Nos"},
            {"item_no": "Glass-103", "item_description": "Micro Pippette 10ml", "item_quantity": "08", "item_uom": "Nos"},
            {"item_no": "Glass-104", "item_description": "Micro Pippette 1-100 micro liter Tips", "item_quantity": "12000", "item_uom": "Nos"},
            {"item_no": "Glass-105", "item_description": "Micro Pippette 1ml Tips", "item_quantity": "4000", "item_uom": "Nos"},
            {"item_no": "Glass-106", "item_description": "Micro Pippette 10ml Tips", "item_quantity": "2000", "item_uom": "Nos"},
            {"item_no": "Glass-107", "item_description": "Head Gear", "item_quantity": "40", "item_uom": "Packs"},
            {"item_no": "Glass-108", "item_description": "Conical Flask with cap 250ml", "item_quantity": "200", "item_uom": "Nos"},
            {"item_no": "Glass-109", "item_description": "Conical Flask with cap 500ml", "item_quantity": "200", "item_uom": "Nos"},
            {"item_no": "Glass-110", "item_description": "Flat Bottom Flask 6000ml", "item_quantity": "08", "item_uom": "Nos"},
            {"item_no": "Glass-111", "item_description": "Gloves Powder Coated (Sterilized)", "item_quantity": "120", "item_uom": "Packs"},
            {"item_no": "Glass-112", "item_description": "Face Masks", "item_quantity": "120", "item_uom": "Packs"},
            {"item_no": "Glass-113", "item_description": "Aluminium Foil", "item_quantity": "08", "item_uom": "Packs"},
            {"item_no": "Glass-114", "item_description": "Sterility Bottles with Cap 100ml", "item_quantity": "800", "item_uom": "Nos"},
            {"item_no": "Glass-115", "item_description": "Sterility Bottles with Cap 250ml", "item_quantity": "800", "item_uom": "Nos"},
            {"item_no": "Glass-116", "item_description": "Sterility Bottles with Cap 500ml", "item_quantity": "400", "item_uom": "Nos"},
            {"item_no": "Glass-117", "item_description": "Sterility Bottles with Cap 1000ml", "item_quantity": "200", "item_uom": "Nos"},
            {"item_no": "Glass-118", "item_description": "Seperator Funnel", "item_quantity": "20", "item_uom": "Nos"},
            {"item_no": "Glass-119", "item_description": "Test Tube (bio Assay)", "item_quantity": "800", "item_uom": "Nos"},
            {"item_no": "Glass-120", "item_description": "Test Tube for endotoxin", "item_quantity": "800", "item_uom": "Nos"},
            {"item_no": "Glass-121", "item_description": "Petri Dishes for Bio assay (plates)", "item_quantity": "400", "item_uom": "Nos"},
            {"item_no": "Glass-122", "item_description": "Cotton", "item_quantity": "80", "item_uom": "Packs"},
            {"item_no": "Glass-123", "item_description": "Filteration Assembly", "item_quantity": "12", "item_uom": "Nos"},
        ],
    },
    {
        "source_name": "official_drap_page_and_pdf",
        "title": "Tender for Supply of Lab Chemicals, Glassware, equipment and reference standards for National Control Laboratory for Biologicals (NCLB), Islamabad during the FY 2023-24",
        "publication_date": "2024-01-10",
        "closing_date": "2024-01-19",
        "buyer": "National Control Laboratory for Biologicals, Drug Regulatory Authority of Pakistan",
        "contract_period": "FY 2023-24",
        "classification": "healthcare tender document",
        "status": "published",
        "notice_id": "tender-for-supply-of-lab-chemicals-glassware-equipment-and-reference-standards-for-national-control-laboratory-for-biologicals-nclb-islamabad-during-the-fy-2023-24",
        "notice_url": "https://www.dra.gov.pk/news_updates/tenders/tender-for-supply-of-lab-chemicals-glassware-equipment-and-reference-standards-for-national-control-laboratory-for-biologicals-nclb-islamabad-during-the-fy-2023-24/",
        "description": "Supply of lab chemicals, glassware, equipment and reference standards for NCLB Islamabad during FY 2023-24.",
        "query_text": "laboratory, glassware, equipment, reference standard, endotoxin, medical, healthcare",
        "items": [
            {"item_no": "NCLB24-01", "item_description": "Ampoule Cutter", "item_quantity": "05", "item_uom": "Nos"},
            {"item_no": "NCLB24-02", "item_description": "Vial Decaper (8mm and 11mm)", "item_quantity": "01", "item_uom": "Nos"},
            {"item_no": "NCLB24-03", "item_description": "Vial Decaper (13mm and 20mm)", "item_quantity": "01", "item_uom": "Nos"},
            {"item_no": "NCLB24-04", "item_description": "Vial Decaper (30mm)", "item_quantity": "01", "item_uom": "Nos"},
            {"item_no": "NCLB24-07", "item_description": "Surgical Mask, three-ply", "item_quantity": "50", "item_uom": "Boxes"},
            {"item_no": "NCLB24-08", "item_description": "Shoe cover (Plastic)", "item_quantity": "2000", "item_uom": "Pairs"},
            {"item_no": "NCLB24-12", "item_description": "Syringes (10mL)", "item_quantity": "02", "item_uom": "Boxes"},
            {"item_no": "NCLB24-13", "item_description": "Chloroxylenol (4.8% W/V)", "item_quantity": "10", "item_uom": "Liters"},
            {"item_no": "NCLB24-14", "item_description": "Rectified Spirit", "item_quantity": "50", "item_uom": "Liters"},
            {"item_no": "NCLB24-15", "item_description": "Iso-propyl Alcohol (70% v/v)", "item_quantity": "50", "item_uom": "Liters"},
            {"item_no": "NCLB24-16", "item_description": "PPE for sterility test (Autoclavable), medium size", "item_quantity": "10", "item_uom": "Units"},
            {"item_no": "NCLB24-17", "item_description": "PPE for sterility test (Autoclavable), large size", "item_quantity": "10", "item_uom": "Units"},
            {"item_no": "NCLB24-18", "item_description": "Cover slip / glass for microscopic glass slides", "item_quantity": "01", "item_uom": "Box"},
            {"item_no": "NCLB24-19", "item_description": "Test Tube for Bacterial Endotoxin Testing (BET)", "item_quantity": "2000", "item_uom": "Units"},
            {"item_no": "NCLB24-20", "item_description": "LAL Test Lysate (for Gel Clot method)", "item_quantity": "10", "item_uom": "Vials"},
            {"item_no": "NCLB24-21", "item_description": "LAL Water", "item_quantity": "15", "item_uom": "Bottles"},
            {"item_no": "NCLB24-22", "item_description": "Positive Control of Endotoxin (CSE)", "item_quantity": "05", "item_uom": "Vials"},
            {"item_no": "NCLB24-23", "item_description": "Filter Paper 0.22um", "item_quantity": "02", "item_uom": "Boxes"},
            {"item_no": "NCLB24-25", "item_description": "pH Buffer 7.0", "item_quantity": "01", "item_uom": "Bottle"},
            {"item_no": "NCLB24-26", "item_description": "pH Buffer 10.0", "item_quantity": "01", "item_uom": "Bottle"},
            {"item_no": "NCLB24-30", "item_description": "Osmometer sampler tips", "item_quantity": "02", "item_uom": "Boxes"},
            {"item_no": "NCLB24-31", "item_description": "Moister Analyzer sampling Pan", "item_quantity": "02", "item_uom": "Boxes"},
            {"item_no": "NCLB24-32", "item_description": "Normal Saline", "item_quantity": "25", "item_uom": "Ampoules"},
            {"item_no": "NCLB24-33", "item_description": "Water for Injection (WFI)", "item_quantity": "100", "item_uom": "Ampoules"},
            {"item_no": "NCLB24-34", "item_description": "Karl Fischer Reagent", "item_quantity": "01", "item_uom": "Set"},
            {"item_no": "NCLB24-35", "item_description": "Tetanus anti-toxin (Equine Origin) for LF Test", "item_quantity": "10", "item_uom": "Ampoules / Vials"},
            {"item_no": "NCLB24-36", "item_description": "Standard tetanus toxoid for LF test", "item_quantity": "05", "item_uom": "Ampoules / Vials"},
            {"item_no": "NCLB24-37", "item_description": "Anti-Diphtheria Serum for flocculation test", "item_quantity": "05", "item_uom": "Ampoules / Vials"},
            {"item_no": "NCLB24-40", "item_description": "Fetal Bovine Serum", "item_quantity": "02", "item_uom": "Bottles"},
            {"item_no": "NCLB24-41", "item_description": "L-Glutamine", "item_quantity": "02", "item_uom": "Bottles"},
            {"item_no": "NCLB24-44", "item_description": "Non-Essential Amino-Acids (100X) for MEM", "item_quantity": "02", "item_uom": "Bottles"},
            {"item_no": "NCLB24-45", "item_description": "Phenol Red", "item_quantity": "02", "item_uom": "Bottles"},
            {"item_no": "NCLB24-46", "item_description": "Fungizone", "item_quantity": "02", "item_uom": "Bottles"},
            {"item_no": "NCLB24-47", "item_description": "Trypsin 1X", "item_quantity": "02", "item_uom": "Bottles"},
            {"item_no": "NCLB24-48", "item_description": "Anti-Polio Antisera (Antibodies type 1)", "item_quantity": "01", "item_uom": "Set"},
        ],
    },
]
