from __future__ import annotations

MEDICAL_SCOPE_EXCLUDED_NOTICE_IDS = {
    "ه.ط 6/2023/2024",
    "smam-2022-2021-93-cancer-center-ext2-adjustment",
    "hada-2019-2018-ext6",
    "smkh-2020-2019-30-ext1",
    "smkh-2020-2019-19-ext1",
    "smkh-2020-2019-07-ext1",
    "smkh-2020-2019-06-ext1",
    "smkh-2020-2019-10-ext1",
    "smkh-2020-2019-03-ext1",
    "smkh-2018-2017-22-ext3",
    "smkh-2017-2016-23-ext7",
    "smkh-2018-2017-22-national-ext1",
    "smkh-2018-2017-2-hajri-ext1",
    "mkh-2020-2019-11-incinerator-ext1",
    "mkhd10-2014-meals-change1",
    "smkh-2012-2011-17-cancer-center-ext",
    "smkh-2022-2021-333-payment-ext1",
    "smkh-2018-2017-2-owaid-ext2",
    "smkh-2018-2017-23-incinerator-ext2",
}

VERIFIED_SEED_ROWS = [
    {
        "source": "CAPT Winning Bids",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2026-05-05",
        "closing_date": "",
        "title": "تعيين مكتب استشاري محلي للقيام بتصميم وترخيص واعداد المخططات والمستندات ووثائق المشروع لمركز تخصصي لطب الأسنان ومبنى مواقف متعددة الادوار لخدمته بمنطقة المرقاب - قطعة (3) والاشراف عليه",
        "description": "تعيين مكتب استشاري محلي للقيام بتصميم وترخيص واعداد المخططات والمستندات ووثائق المشروع لمركز تخصصي لطب الأسنان ومبنى مواقف متعددة الادوار لخدمته بمنطقة المرقاب - قطعة (3) والاشراف عليه",
        "buyer": "Ministry of Health",
        "classification": "winning bid",
        "status": "awarded",
        "currency": "KWD",
        "amount": "774643.000",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "دار الخليج للاستشارات الهندسية",
        "awarded_date": "2026-05-05",
        "awarded_value_detail": "774,643.000 KD",
        "contract_period": "",
        "item_no": "10",
        "item_description": "تعيين مكتب استشاري محلي للقيام بتصميم وترخيص واعداد المخططات والمستندات ووثائق المشروع لمركز تخصصي لطب الأسنان ومبنى مواقف متعددة الادوار لخدمته بمنطقة المرقاب - قطعة (3) والاشراف عليه",
        "item_uom": "",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "774643.000",
        "notice_id": "ه.ط 6/2023/2024",
        "notice_url": "https://capt.gov.kw/en/tenders/winning-bids/?meeting_date_from=2024-01-01&meeting_date_to=2026-05-28&form=date&page=1",
        "query_text": "health, ministry of health",
        "dedup_key": "capt-page1-medical-row-10",
        "title_english": "Appointment of a local consulting office to carry out the design, licensing, preparation of plans, documents and project documents for a specialized dentistry center and a multi-storey parking building to serve it in Al-Mirqab area - plot (3) and supervision",
        "description_english": "Appointment of a local consulting office to carry out the design, licensing, preparation of plans, documents and project documents for a specialized dentistry center and a multi-storey parking building to serve it in Al-Mirqab area - plot (3) and supervision",
        "buyer_english": "Ministry of Health",
        "classification_english": "winning bid",
        "status_english": "awarded",
        "awarding_agency_name_english": "Ministry of Health",
        "supplier_name_english": "Dar Al Khaleej Engineering Consultants",
        "contract_period_english": "",
        "item_description_english": "Appointment of a local consulting office to carry out the design, licensing, preparation of plans, documents and project documents for a specialized dentistry center and a multi-storey parking building to serve it in Al-Mirqab area - plot (3) and supervision",
        "query_text_english": "health, ministry of health",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-01-19",
        "closing_date": "",
        "title": "Direct contract amendment approval for feeding tubes for all hospital departments",
        "description": "CAPT board minutes meeting 2025/3 record approval to amend the Ministry of Health direct contract file 4GR030 for purchasing feeding tubes required by all hospital departments, correcting the represented principal from AVANOS to AVANOS MEDICAL / AVANOS HEALTH in the contract with Delta Med International General Trading and Contracting due to a typographical error in earlier approvals.",
        "buyer": "Ministry of Health",
        "classification": "direct contract amendment approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "271670",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Delta Med International General Trading and Contracting / AVANOS MEDICAL / AVANOS HEALTH",
        "awarded_date": "2025-01-13",
        "awarded_value_detail": "271,670 KWD",
        "contract_period": "",
        "item_no": "9",
        "item_description": "Purchase of feeding tubes for the needs of all hospital departments",
        "item_uom": "",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "271670",
        "notice_id": "4GR030-change-principal1",
        "notice_url": "https://files.capt.gov.kw/media/c9787dd6-973c-44aa-b21d-6293a5a134f9.pdf",
        "query_text": "feeding tubes, hospitals, ministry of health, medical supplies, avanos medical",
        "dedup_key": "capt-board-2025-3-4gr030-change-principal1",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-12-15",
        "closing_date": "",
        "title": "First extension approval for contract 70 covering maintenance of 2647 medical devices with spare parts",
        "description": "CAPT board minutes meeting 2024/73 record approval of the first extension for contract 70 covering comprehensive maintenance of 2647 medical devices with spare parts with Al Taqadum Technology, as local agent and supplier for the manufacturing companies, from 2024-09-01 until 2025-03-31 to preserve continuity of operation.",
        "buyer": "Ministry of Health",
        "classification": "contract extension approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "1315344.917",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Al Taqadum Technology",
        "awarded_date": "2024-12-09",
        "awarded_value_detail": "1,315,344.917 KWD",
        "contract_period": "2024-09-01 to 2025-03-31",
        "item_no": "44",
        "item_description": "Comprehensive maintenance of 2647 medical devices with spare parts",
        "item_uom": "devices",
        "item_quantity": "2647",
        "item_unit_price": "",
        "item_awarded_value": "1315344.917",
        "notice_id": "contract-70-medical-devices-ext1",
        "notice_url": "https://files.capt.gov.kw/media/dfa92963-8390-410b-bdd1-6dc4f5894df9.pdf",
        "query_text": "medical devices, maintenance, spare parts, ministry of health, healthcare",
        "dedup_key": "capt-board-2024-73-contract-70-medical-devices-ext1",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-12-15",
        "closing_date": "",
        "title": "Second extension amount adjustment approval for Kuwait Cancer Center project consulting contract",
        "description": "CAPT board minutes meeting 2024/73 record approval to adjust the second extension amount for contract S/M AM/2022/2021/93 relating to design review and completion support for the Kuwait Cancer Center project, contracted with Dar Al Sur for Engineering Consultations, so the amount becomes 293,096.538 KWD instead of 267,573.810 KWD.",
        "buyer": "Ministry of Health",
        "classification": "contract extension approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "293096.538",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Dar Al Sur for Engineering Consultations",
        "awarded_date": "2024-12-09",
        "awarded_value_detail": "293,096.538 KWD adjusted amount",
        "contract_period": "",
        "item_no": "46",
        "item_description": "Design review and completion support services for the Kuwait Cancer Center project",
        "item_uom": "consulting contract",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "293096.538",
        "notice_id": "smam-2022-2021-93-cancer-center-ext2-adjustment",
        "notice_url": "https://files.capt.gov.kw/media/dfa92963-8390-410b-bdd1-6dc4f5894df9.pdf",
        "query_text": "cancer center, medical project, engineering consultation, ministry of health, healthcare",
        "dedup_key": "capt-board-2024-73-smam-2022-2021-93-cancer-center-ext2-adjustment",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-12-15",
        "closing_date": "",
        "title": "Direct contract value adjustment approval for genetic medical screening laboratory materials",
        "description": "CAPT board minutes meeting 2024/73 record approval of Ministry of Health request 7660 dated 2024-11-26 to amend direct contract file 451LB3 for purchase of laboratory materials for genetic medical screening tests needed by the laboratory of the Genetics Diseases Center, with ITB Medical for Food Products and Health Plants, reducing the total to 209,084.150 KWD instead of 244,125 KWD based on State Audit Bureau observations.",
        "buyer": "Ministry of Health",
        "classification": "contract value adjustment approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "209084.150",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "ITB Medical for Food Products and Health Plants",
        "awarded_date": "2024-12-09",
        "awarded_value_detail": "Revised to 209,084.150 KWD instead of 244,125 KWD based on State Audit Bureau observations",
        "contract_period": "",
        "item_no": "40",
        "item_description": "Laboratory materials for genetic medical screening tests for the Genetics Diseases Center laboratory",
        "item_uom": "contract",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "209084.150",
        "notice_id": "451lb3-genetic-screening-lab-materials-adjustment",
        "notice_url": "https://files.capt.gov.kw/media/dfa92963-8390-410b-bdd1-6dc4f5894df9.pdf",
        "query_text": "laboratory materials, genetic screening, ministry of health, medical tests, contract value adjustment",
        "dedup_key": "capt-board-2024-73-451lb3-genetic-screening-lab-materials-adjustment",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-12-15",
        "closing_date": "",
        "title": "Contract value adjustment approval for Gulf Tender 38 hospital supplies item",
        "description": "CAPT board minutes meeting 2024/73 record approval of Ministry of Health request 7547 dated 2024-11-25 to amend the value of item number 1 under Gulf Tender 38 for supply of hospital-use items with Alghanim Healthcare General Trading, on behalf of The National Medical Products Co. Ltd. (DAMAD), reducing the contract item value to 911,700 USD, equivalent to 282,627 KWD, instead of the earlier 2,424,700 USD after cancellation of some items at the request of the State Audit Bureau.",
        "buyer": "Ministry of Health",
        "classification": "contract value adjustment approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "282627",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Alghanim Healthcare General Trading / The National Medical Products Co. Ltd. (DAMAD)",
        "awarded_date": "2024-12-09",
        "awarded_value_detail": "Revised to 911,700 USD equivalent to 282,627 KWD instead of 2,424,700 USD after cancellation of some items",
        "contract_period": "",
        "item_no": "43",
        "item_description": "Item number 1 under Gulf Tender 38 for supply of hospital-use items",
        "item_uom": "item",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "282627",
        "notice_id": "gulf-38-item1-value-adjustment",
        "notice_url": "https://files.capt.gov.kw/media/dfa92963-8390-410b-bdd1-6dc4f5894df9.pdf",
        "query_text": "hospital supplies, ministry of health, contract value adjustment, national medical products, alghanim healthcare",
        "dedup_key": "capt-board-2024-73-gulf-38-item1-value-adjustment",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-12-15",
        "closing_date": "",
        "title": "Contract date and value change notification for medical devices maintenance contract 970",
        "description": "CAPT board minutes meeting 2024/73 record that the board was informed of a Ministry of Health change to contract 970 for maintenance of medical devices including spare parts with Al Taqadum Technology, making the effective period 2024-12-01 to 2025-03-31 and reducing the total to 239,760.918 KWD instead of 661,465.855 KWD after State Audit Bureau approval.",
        "buyer": "Ministry of Health",
        "classification": "contract amendment notification",
        "status": "awarded",
        "currency": "KWD",
        "amount": "239760.918",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Al Taqadum Technology",
        "awarded_date": "2024-12-09",
        "awarded_value_detail": "Changed to 239,760.918 KWD instead of 661,465.855 KWD after State Audit Bureau approval",
        "contract_period": "2024-12-01 to 2025-03-31",
        "item_no": "42",
        "item_description": "Maintenance of medical devices including spare parts for contract 970",
        "item_uom": "contract",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "239760.918",
        "notice_id": "970-medical-devices-maintenance-change-notification",
        "notice_url": "https://files.capt.gov.kw/media/dfa92963-8390-410b-bdd1-6dc4f5894df9.pdf",
        "query_text": "medical devices, maintenance, spare parts, ministry of health, contract change notification",
        "dedup_key": "capt-board-2024-73-970-medical-devices-maintenance-change-notification",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "Direct contract 171 for maintenance of 125 medical devices with spare parts for FY 2024-2025",
        "description": "CAPT board minutes meeting 2024/10 record Ministry of Health direct contract request 171 for maintenance of 125 medical devices by Al Taqadum Technology from 2024-05-01 to 2025-03-31.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "146142.132",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Al Taqadum Technology",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "146,142.132 KWD",
        "contract_period": "2024-05-01 to 2025-03-31",
        "item_no": "171",
        "item_description": "Maintenance of 125 medical devices with spare parts for FY 2024-2025",
        "item_uom": "devices",
        "item_quantity": "125",
        "item_unit_price": "",
        "item_awarded_value": "146142.132",
        "notice_id": "171",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "medical device, ministry of health, maintenance",
        "dedup_key": "capt-board-2024-10-171",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "Direct contract 3LB521 for PAP/PREP THIN test solutions for cervical screening laboratories",
        "description": "CAPT board minutes meeting 2024/10 record Ministry of Health direct contract 3LB521 to purchase KIT TEST PAP / PREP THIN solutions for cervical screening laboratories from Nejma Burgan General Trading & Contracting on behalf of Hologic.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "237837.600",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Nejma Burgan General Trading & Contracting / Hologic",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "237,837.600 KWD",
        "contract_period": "",
        "item_no": "3LB521",
        "item_description": "PAP / PREP THIN kit test solutions for cervical screening laboratories",
        "item_uom": "",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "237837.600",
        "notice_id": "3LB521",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "laboratory, cervical screening, medical, ministry of health",
        "dedup_key": "capt-board-2024-10-3lb521",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "Direct contract 4TB027 for levetiracetam 500 mg tablets for neurology and epilepsy patients",
        "description": "CAPT board minutes meeting 2024/10 record Ministry of Health direct contract 4TB027 to purchase levetiracetam 500 mg tablets for neurology and epilepsy patients from Mohammad Naser Al Hajri & Sons on behalf of GlaxoSmithKline Limited Export.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "1408150",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Mohammad Naser Al Hajri & Sons / GlaxoSmithKline Limited Export",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "1,408,150 KWD",
        "contract_period": "",
        "item_no": "4TB027",
        "item_description": "Levetiracetam 500 mg tablets for neurology and epilepsy patients",
        "item_uom": "tablets",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "1408150",
        "notice_id": "4TB027",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "medicine, neurology, epilepsy, ministry of health",
        "dedup_key": "capt-board-2024-10-4tb027",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "Direct contract 634 for maintenance of 279 medical devices with spare parts for FY 2024-2025",
        "description": "CAPT board minutes meeting 2024/10 record Ministry of Health direct contract 634 for maintenance of 279 medical devices by Al Taqadum Technology from 2024-05-01 to 2025-03-31.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "158366.079",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Al Taqadum Technology",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "158,366.079 KWD",
        "contract_period": "2024-05-01 to 2025-03-31",
        "item_no": "634",
        "item_description": "Maintenance of 279 medical devices with spare parts for FY 2024-2025",
        "item_uom": "devices",
        "item_quantity": "279",
        "item_unit_price": "",
        "item_awarded_value": "158366.079",
        "notice_id": "634",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "medical device, ministry of health, maintenance",
        "dedup_key": "capt-board-2024-10-634",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "Direct contract 646 for maintenance of 8 medical devices with spare parts for FY 2024-2025",
        "description": "CAPT board minutes meeting 2024/10 record Ministry of Health direct contract 646 for maintenance of 8 medical devices by Al Taqadum Technology from 2024-05-01 to 2025-03-31.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "88873.308",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Al Taqadum Technology",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "88,873.308 KWD",
        "contract_period": "2024-05-01 to 2025-03-31",
        "item_no": "646",
        "item_description": "Maintenance of 8 medical devices with spare parts for FY 2024-2025",
        "item_uom": "devices",
        "item_quantity": "8",
        "item_unit_price": "",
        "item_awarded_value": "88873.308",
        "notice_id": "646",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "medical device, ministry of health, maintenance",
        "dedup_key": "capt-board-2024-10-646",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "Direct contract 647 for maintenance of 27 radiology devices with spare parts",
        "description": "CAPT board minutes meeting 2024/10 record Ministry of Health direct contract 647 for maintenance of 27 radiology devices by Al Taqadum Technology from 2024-05-01 to 2025-03-31.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "76915.667",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Al Taqadum Technology",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "76,915.667 KWD",
        "contract_period": "2024-05-01 to 2025-03-31",
        "item_no": "647",
        "item_description": "Maintenance of 27 radiology devices with spare parts",
        "item_uom": "devices",
        "item_quantity": "27",
        "item_unit_price": "",
        "item_awarded_value": "76915.667",
        "notice_id": "647",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "radiology, medical device, ministry of health, maintenance",
        "dedup_key": "capt-board-2024-10-647",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "Direct contract 979 for maintenance of 151 medical devices with spare parts for FY 2024-2025",
        "description": "CAPT board minutes meeting 2024/10 record Ministry of Health direct contract 979 for maintenance of 151 medical devices by Al Taqadum Technology from 2024-05-01 to 2025-03-31.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "148158.880",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Al Taqadum Technology",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "148,158.880 KWD",
        "contract_period": "2024-05-01 to 2025-03-31",
        "item_no": "979",
        "item_description": "Maintenance of 151 medical devices with spare parts for FY 2024-2025",
        "item_uom": "devices",
        "item_quantity": "151",
        "item_unit_price": "",
        "item_awarded_value": "148158.880",
        "notice_id": "979",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "medical device, ministry of health, maintenance",
        "dedup_key": "capt-board-2024-10-979",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "Direct contract 980 for maintenance of 107 medical devices with spare parts for FY 2024-2025",
        "description": "CAPT board minutes meeting 2024/10 record Ministry of Health direct contract 980 for maintenance of 107 medical devices by Al Taqadum Technology from 2024-05-01 to 2025-03-31.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "144346.492",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Al Taqadum Technology",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "144,346.492 KWD",
        "contract_period": "2024-05-01 to 2025-03-31",
        "item_no": "980",
        "item_description": "Maintenance of 107 medical devices with spare parts for FY 2024-2025",
        "item_uom": "devices",
        "item_quantity": "107",
        "item_unit_price": "",
        "item_awarded_value": "144346.492",
        "notice_id": "980",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "medical device, ministry of health, maintenance",
        "dedup_key": "capt-board-2024-10-980",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "Approval to supply dialysis solutions from Gulf Tender No. 16",
        "description": "CAPT board minutes meeting 2024/10 record Ministry of Health approval to supply industrial dialysis solutions from Gulf Tender No. 16 through the permanent unified purchasing committee of the GCC Executive Office.",
        "buyer": "Ministry of Health",
        "classification": "supply approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "1699267",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Companies listed in Ministry of Health letter",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "1,699,267 KWD",
        "contract_period": "",
        "item_no": "Gulf-16",
        "item_description": "Supply of industrial dialysis solutions",
        "item_uom": "",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "1699267",
        "notice_id": "Gulf-16",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "dialysis, kidney, ministry of health, medical",
        "dedup_key": "capt-board-2024-10-gulf-16",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-05-04",
        "closing_date": "",
        "title": "Sixth extension approval for resident care contract with medical and scientific devices company",
        "description": "CAPT board minutes meeting 2025/39 record approval of the sixth extension of resident service contract tender H A Sh D I (1) 2019/2018 for the Public Authority for Disability Affairs with Al Eissa Medical and Scientific Devices Company until completion of the replacement tender procedures.",
        "buyer": "Public Authority for Disability Affairs",
        "classification": "contract extension approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "1804646.880",
        "awarding_agency_name": "Public Authority for Disability Affairs",
        "supplier_name": "Al Eissa Medical and Scientific Devices Company",
        "awarded_date": "2025-04-30",
        "awarded_value_detail": "1,804,646.880 KWD",
        "contract_period": "2025-04-01 to 2026-03-31",
        "item_no": "24",
        "item_description": "Sixth extension of resident service contract tender H A Sh D I (1) 2019/2018",
        "item_uom": "contract",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "1804646.880",
        "notice_id": "hada-2019-2018-ext6",
        "notice_url": "https://files.capt.gov.kw/media/1c1c6a9f-ce7d-4088-9a8c-8522411d28be.pdf",
        "query_text": "disability, medical devices, healthcare service, extension",
        "dedup_key": "capt-board-2025-39-hada-ext6",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-05-11",
        "closing_date": "",
        "title": "Direct contract 4AK042 for CAPD 2L 2.27% peritoneal dialysis solution",
        "description": "CAPT board minutes meeting 2025/40 record Ministry of Health direct contract 4AK042 to purchase CAPD 2L 2.27% peritoneal dialysis solution for kidney dialysis centers from Al Taqadum Technology on behalf of Baxter Company Ltd.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "189000",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Al Taqadum Technology / Baxter Company Ltd",
        "awarded_date": "2025-05-05",
        "awarded_value_detail": "189,000 KWD",
        "contract_period": "",
        "item_no": "22",
        "item_description": "CAPD 2L 2.27% peritoneal dialysis solution for kidney dialysis centers",
        "item_uom": "2L bags",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "189000",
        "notice_id": "4AK042",
        "notice_url": "https://files.capt.gov.kw/media/62143405-06f1-4202-97ca-ec50d07f97ca.pdf",
        "query_text": "dialysis, kidney, peritoneal dialysis, solution, ministry of health",
        "dedup_key": "capt-board-2025-40-4ak042",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-05-11",
        "closing_date": "",
        "title": "Direct contract 4AK048 for organ preservation solution bags",
        "description": "CAPT board minutes meeting 2025/40 record Ministry of Health direct contract 4AK048 to purchase PERFUSION ORGAN BAG UNIT ML2000 CUSTODIOL preservation solution for Hamad Al Essa organ transplant center from Fourth Dimension Medical on behalf of Dr. F. Kohler PharmaPal Ltd.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "80000",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Fourth Dimension Medical / Dr. F. Kohler PharmaPal Ltd",
        "awarded_date": "2025-05-05",
        "awarded_value_detail": "80,000 KWD",
        "contract_period": "",
        "item_no": "23",
        "item_description": "PERFUSION ORGAN BAG UNIT ML2000 CUSTODIOL organ preservation solution for organ transplant procedures",
        "item_uom": "bags",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "80000",
        "notice_id": "4AK048",
        "notice_url": "https://files.capt.gov.kw/media/62143405-06f1-4202-97ca-ec50d07f97ca.pdf",
        "query_text": "organ transplant, preservation solution, ministry of health, medical",
        "dedup_key": "capt-board-2025-40-4ak048",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-05-11",
        "closing_date": "",
        "title": "Direct contract 4AK055 for CAPD 2L 1.36% peritoneal dialysis solution",
        "description": "CAPT board minutes meeting 2025/40 record Ministry of Health direct contract 4AK055 to purchase CAPD BAG/D 2L 1.36% peritoneal dialysis solution for kidney dialysis centers from Al Taqadum Technology on behalf of Baxter Company Ltd.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "132300",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Al Taqadum Technology / Baxter Company Ltd",
        "awarded_date": "2025-05-05",
        "awarded_value_detail": "132,300 KWD",
        "contract_period": "",
        "item_no": "24",
        "item_description": "CAPD BAG/D 2L 1.36% peritoneal dialysis solution for kidney dialysis centers",
        "item_uom": "2L bags",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "132300",
        "notice_id": "4AK055",
        "notice_url": "https://files.capt.gov.kw/media/62143405-06f1-4202-97ca-ec50d07f97ca.pdf",
        "query_text": "dialysis, kidney, peritoneal dialysis, solution, ministry of health",
        "dedup_key": "capt-board-2025-40-4ak055",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-05-11",
        "closing_date": "",
        "title": "Direct contract 057AK4 for HAEMOSOL BO bags used with PRISMAFLEX continuous renal dialysis",
        "description": "CAPT board minutes meeting 2025/40 record Ministry of Health direct contract 057AK4 to purchase HAEMOSOL BO bags used with PRISMAFLEX continuous renal dialysis at kidney dialysis centers from Al Taqadum Technology on behalf of Baxter Vantive (formerly Baxter GmbH).",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "840000",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Al Taqadum Technology / Baxter Vantive (formerly Baxter GmbH)",
        "awarded_date": "2025-05-05",
        "awarded_value_detail": "840,000 KWD",
        "contract_period": "",
        "item_no": "26",
        "item_description": "HAEMOSOL BO bags used with PRISMAFLEX continuous renal dialysis for kidney dialysis centers",
        "item_uom": "bags",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "840000",
        "notice_id": "057AK4",
        "notice_url": "https://files.capt.gov.kw/media/62143405-06f1-4202-97ca-ec50d07f97ca.pdf",
        "query_text": "dialysis, kidney, haemosol, prismaflex, ministry of health",
        "dedup_key": "capt-board-2025-40-057ak4",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-05-11",
        "closing_date": "",
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-05-11",
        "closing_date": "",
        "title": "Direct contract 4AK064 for automated peritoneal dialysis solution 1.5% 2L",
        "description": "CAPT board minutes meeting 2025/40 record Ministry of Health direct contract 4AK064 to purchase SLEEP-SAFE CAPD5 D.SOLN.P 1.5% 2L automated peritoneal dialysis solution for kidney dialysis centers from Mohammad Naser Al Hajri & Sons on behalf of Care Medical Fresenius.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "96460",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Mohammad Naser Al Hajri & Sons / Care Medical Fresenius",
        "awarded_date": "2025-05-05",
        "awarded_value_detail": "96,460 KWD",
        "contract_period": "",
        "item_no": "28",
        "item_description": "SLEEP-SAFE CAPD5 D.SOLN.P 1.5% 2L automated peritoneal dialysis solution",
        "item_uom": "2L bags",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "96460",
        "notice_id": "4AK064",
        "notice_url": "https://files.capt.gov.kw/media/62143405-06f1-4202-97ca-ec50d07f97ca.pdf",
        "query_text": "dialysis, kidney, peritoneal dialysis, ministry of health",
        "dedup_key": "capt-board-2025-40-4ak064",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-05-11",
        "closing_date": "",
        "title": "Direct contract 4AK066 for automated peritoneal dialysis supplies and solution 2.3% 4L",
        "description": "CAPT board minutes meeting 2025/40 record Ministry of Health direct contract 4AK066 to purchase automated peritoneal dialysis supplies and SLEEP-SAFE CAPD5 D.SOLN.P 2.3% 4L solution for kidney dialysis centers from Mohammad Naser Al Hajri & Sons on behalf of Care Medical Fresenius.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "90180",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Mohammad Naser Al Hajri & Sons / Care Medical Fresenius",
        "awarded_date": "2025-05-05",
        "awarded_value_detail": "90,180 KWD",
        "contract_period": "",
        "item_no": "29",
        "item_description": "Automated peritoneal dialysis supplies and SLEEP-SAFE CAPD5 D.SOLN.P 2.3% 4L solution",
        "item_uom": "4L bags",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "90180",
        "notice_id": "4AK066",
        "notice_url": "https://files.capt.gov.kw/media/62143405-06f1-4202-97ca-ec50d07f97ca.pdf",
        "query_text": "dialysis, kidney, peritoneal dialysis, supplies, ministry of health",
        "dedup_key": "capt-board-2025-40-4ak066",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-05-11",
        "closing_date": "",
        "title": "Direct contract 51AKD4 for blood tubing used during hemodialysis",
        "description": "CAPT board minutes meeting 2025/40 record Ministry of Health direct contract 51AKD4 to purchase ARTISET PREPOST/B.HAEMO blood tubing used during hemodialysis for kidney dialysis centers from Al Taqadum Technology on behalf of Baxter Vantive.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "4240000",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Al Taqadum Technology / Baxter Vantive",
        "awarded_date": "2025-05-05",
        "awarded_value_detail": "4,240,000 KWD",
        "contract_period": "",
        "item_no": "31",
        "item_description": "ARTISET PREPOST/B.HAEMO blood tubing for hemodialysis",
        "item_uom": "sets",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "4240000",
        "notice_id": "51AKD4",
        "notice_url": "https://files.capt.gov.kw/media/62143405-06f1-4202-97ca-ec50d07f97ca.pdf",
        "query_text": "hemodialysis, blood tubing, kidney, ministry of health",
        "dedup_key": "capt-board-2025-40-51akd4",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-05-11",
        "closing_date": "",
        "title": "Direct contract 4IN499 for levetiracetam injection",
        "description": "CAPT board minutes meeting 2025/40 record Ministry of Health direct contract 4IN499 to purchase KEPPRA levetiracetam 500 mg/5 ml injection for hospitals from Mohammad Naser Al Hajri & Sons on behalf of GlaxoSmithKline Limited Export.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "2286144",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Mohammad Naser Al Hajri & Sons / GlaxoSmithKline Limited Export",
        "awarded_date": "2025-05-05",
        "awarded_value_detail": "2,286,144 KWD",
        "contract_period": "",
        "item_no": "32",
        "item_description": "KEPPRA levetiracetam 500 mg/5 ml injection",
        "item_uom": "injections",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "2286144",
        "notice_id": "4IN499",
        "notice_url": "https://files.capt.gov.kw/media/62143405-06f1-4202-97ca-ec50d07f97ca.pdf",
        "query_text": "levetiracetam, injection, neurology, ministry of health",
        "dedup_key": "capt-board-2025-40-4in499",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-05-11",
        "closing_date": "",
        "title": "Direct contract 4IN508 for ANDEXXA 200 mg injection",
        "description": "CAPT board minutes meeting 2025/40 record Ministry of Health direct contract 4IN508 to purchase ANDEXXA 200 mg injection for hematology treatment in hospitals from Al Mojel Drugs on behalf of Alexion AstraZeneca.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "442762.880",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Al Mojel Drugs / Alexion AstraZeneca",
        "awarded_date": "2025-05-05",
        "awarded_value_detail": "442,762.880 KWD",
        "contract_period": "",
        "item_no": "33",
        "item_description": "ANDEXXA 200 mg injection for hematology treatment",
        "item_uom": "vials",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "442762.880",
        "notice_id": "4IN508",
        "notice_url": "https://files.capt.gov.kw/media/62143405-06f1-4202-97ca-ec50d07f97ca.pdf",
        "query_text": "hematology, injection, medicine, ministry of health",
        "dedup_key": "capt-board-2025-40-4in508",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-05-11",
        "closing_date": "",
        "title": "Direct contract 204ON4 for oxaliplatin injection for cancer treatment",
        "description": "CAPT board minutes meeting 2025/40 record Ministry of Health direct contract 204ON4 to purchase ELOXATIN oxaliplatin 200 mg injection for cancer patients at Hassan Makki Juma Specialized Surgery Center from Warba Medical Supplies on behalf of GES Pharma EBEWE.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "184200",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Warba Medical Supplies / GES Pharma EBEWE",
        "awarded_date": "2025-05-05",
        "awarded_value_detail": "184,200 KWD",
        "contract_period": "",
        "item_no": "34",
        "item_description": "ELOXATIN oxaliplatin 200 mg injection for cancer treatment",
        "item_uom": "injections",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "184200",
        "notice_id": "204ON4",
        "notice_url": "https://files.capt.gov.kw/media/62143405-06f1-4202-97ca-ec50d07f97ca.pdf",
        "query_text": "oncology, cancer, oxaliplatin, ministry of health",
        "dedup_key": "capt-board-2025-40-204on4",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-05-11",
        "closing_date": "",
        "title": "Direct contract 4TB408 for valganciclovir 450 mg tablets",
        "description": "CAPT board minutes meeting 2025/40 record Ministry of Health direct contract 4TB408 to purchase VALCYTE valganciclovir 450 mg antiviral tablets for hospitals from Ali Abdulwahab Al Mutawa Commercial Company on behalf of Cheplapharm.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "1185120",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Ali Abdulwahab Al Mutawa Commercial Company / Cheplapharm",
        "awarded_date": "2025-05-05",
        "awarded_value_detail": "1,185,120 KWD",
        "contract_period": "",
        "item_no": "35",
        "item_description": "VALCYTE valganciclovir 450 mg antiviral tablets",
        "item_uom": "tablets",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "1185120",
        "notice_id": "4TB408",
        "notice_url": "https://files.capt.gov.kw/media/62143405-06f1-4202-97ca-ec50d07f97ca.pdf",
        "query_text": "antiviral, valganciclovir, tablets, ministry of health",
        "dedup_key": "capt-board-2025-40-4tb408",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-05-11",
        "closing_date": "",
        "title": "Direct contract 4TB494 for ezetimibe 10 mg tablets",
        "description": "CAPT board minutes meeting 2025/40 record Ministry of Health direct contract 4TB494 to purchase EZETROL ezetimibe 10 mg tablets for heart disease treatment in health centers and hospitals from Ahfad Hamad Saleh Al Humaidhi Pharmaceutical Company on behalf of MSD.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "8253000",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Ahfad Hamad Saleh Al Humaidhi Pharmaceutical Company / MSD",
        "awarded_date": "2025-05-05",
        "awarded_value_detail": "8,253,000 KWD",
        "contract_period": "",
        "item_no": "36",
        "item_description": "EZETROL ezetimibe 10 mg tablets for heart disease treatment",
        "item_uom": "tablets",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "8253000",
        "notice_id": "4TB494",
        "notice_url": "https://files.capt.gov.kw/media/62143405-06f1-4202-97ca-ec50d07f97ca.pdf",
        "query_text": "cardiology, ezetimibe, tablets, ministry of health",
        "dedup_key": "capt-board-2025-40-4tb494",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-05-11",
        "closing_date": "",
        "title": "Direct contract 4TB497 for mycophenolic acid 360 mg tablets",
        "description": "CAPT board minutes meeting 2025/40 record Ministry of Health direct contract 4TB497 to purchase MYFORTIC mycophenolic acid 360 mg tablets for kidney transplant patients from Al Mojel Drugs on behalf of Novartis Pharma.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "768774.600",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Al Mojel Drugs / Novartis Pharma",
        "awarded_date": "2025-05-05",
        "awarded_value_detail": "768,774.600 KWD",
        "contract_period": "",
        "item_no": "37",
        "item_description": "MYFORTIC mycophenolic acid 360 mg tablets for kidney transplant patients",
        "item_uom": "tablets",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "768774.600",
        "notice_id": "4TB497",
        "notice_url": "https://files.capt.gov.kw/media/62143405-06f1-4202-97ca-ec50d07f97ca.pdf",
        "query_text": "transplant, immunosuppressant, kidney, ministry of health",
        "dedup_key": "capt-board-2025-40-4tb497",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-05-11",
        "closing_date": "",
        "title": "Direct contract 4TB505 for tofacitinib 5 mg tablets",
        "description": "CAPT board minutes meeting 2025/40 record Ministry of Health direct contract 4TB505 to purchase XELJANZ tofacitinib 5 mg tablets for rheumatoid arthritis treatment from Ahfad Hamad Saleh Al Humaidhi Pharmaceutical Company on behalf of Pfizer.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "1613370",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Ahfad Hamad Saleh Al Humaidhi Pharmaceutical Company / Pfizer",
        "awarded_date": "2025-05-05",
        "awarded_value_detail": "1,613,370 KWD",
        "contract_period": "",
        "item_no": "38",
        "item_description": "XELJANZ tofacitinib 5 mg tablets for rheumatoid arthritis treatment",
        "item_uom": "tablets",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "1613370",
        "notice_id": "4TB505",
        "notice_url": "https://files.capt.gov.kw/media/62143405-06f1-4202-97ca-ec50d07f97ca.pdf",
        "query_text": "rheumatology, tofacitinib, tablets, ministry of health",
        "dedup_key": "capt-board-2025-40-4tb505",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-05-11",
        "closing_date": "",
        "title": "Direct contract 510TB4 for apremilast 30 mg tablets",
        "description": "CAPT board minutes meeting 2025/40 record Ministry of Health direct contract 510TB4 to purchase OTEZLA apremilast 30 mg tablets for psoriasis patients from Ahfad Hamad Saleh Al Humaidhi Pharmaceutical Company on behalf of Amgen Europe.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "583440",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Ahfad Hamad Saleh Al Humaidhi Pharmaceutical Company / Amgen Europe",
        "awarded_date": "2025-05-05",
        "awarded_value_detail": "583,440 KWD",
        "contract_period": "",
        "item_no": "39",
        "item_description": "OTEZLA apremilast 30 mg tablets for psoriasis treatment",
        "item_uom": "tablets",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "583440",
        "notice_id": "510TB4",
        "notice_url": "https://files.capt.gov.kw/media/62143405-06f1-4202-97ca-ec50d07f97ca.pdf",
        "query_text": "psoriasis, apremilast, tablets, ministry of health",
        "dedup_key": "capt-board-2025-40-510tb4",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-05-11",
        "closing_date": "",
        "title": "Direct contract 4TB522 for BYLVAY SR ODEVIXIBAT 400 mcg capsules",
        "description": "CAPT board minutes meeting 2025/40 record Ministry of Health direct contract 4TB522 to purchase BYLVAY SR ODEVIXIBAT 400 mcg capsules for treatment associated with progressive familial intrahepatic cholestasis from Ali Abdulwahab Al Mutawa Commercial Company on behalf of Patheon / Almafio Pharma Service Ltd. / Ipsen Pharma.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "133363.800",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Ali Abdulwahab Al Mutawa Commercial Company / Patheon / Almafio Pharma Service Ltd. / Ipsen Pharma",
        "awarded_date": "2025-05-05",
        "awarded_value_detail": "133,363.800 KWD",
        "contract_period": "",
        "item_no": "40",
        "item_description": "BYLVAY SR ODEVIXIBAT 400 mcg capsules for treatment associated with progressive familial intrahepatic cholestasis",
        "item_uom": "capsules",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "133363.800",
        "notice_id": "4TB522",
        "notice_url": "https://files.capt.gov.kw/media/62143405-06f1-4202-97ca-ec50d07f97ca.pdf",
        "query_text": "pediatric, odevixibat, bylvay, capsules, ministry of health",
        "dedup_key": "capt-board-2025-40-4tb522",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-05-11",
        "closing_date": "",
        "title": "Direct contract 5EY009 for vitrectomy consumables for ALCON ophthalmology devices",
        "description": "CAPT board minutes meeting 2025/40 record Ministry of Health direct contract 5EY009 to purchase G COMBINED CONST23 vitrectomy consumables for ALCON white and retinal ophthalmology devices from Al Ameen Medical Company on behalf of ALCON.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "2236488",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Al Ameen Medical Company / ALCON",
        "awarded_date": "2025-05-05",
        "awarded_value_detail": "2,236,488 KWD",
        "contract_period": "",
        "item_no": "41",
        "item_description": "G COMBINED CONST23 vitrectomy consumables for ALCON white and retinal ophthalmology devices",
        "item_uom": "consumables",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "2236488",
        "notice_id": "5EY009",
        "notice_url": "https://files.capt.gov.kw/media/62143405-06f1-4202-97ca-ec50d07f97ca.pdf",
        "query_text": "ophthalmology, eye devices, consumables, ministry of health",
        "dedup_key": "capt-board-2025-40-5ey009",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-05-11",
        "closing_date": "",
        "title": "Direct contract 5IN026 for liposomal amphotericin B 50 mg injection",
        "description": "CAPT board minutes meeting 2025/40 record Ministry of Health direct contract 5IN026 to purchase liposomal amphotericin B 50 mg injection for treatment of fungal infections in hospitals from Warba Medical Supplies on behalf of Gilead Sciences Inc.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "1579200",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Warba Medical Supplies / Gilead Sciences Inc.",
        "awarded_date": "2025-05-05",
        "awarded_value_detail": "1,579,200 KWD",
        "contract_period": "",
        "item_no": "42",
        "item_description": "Liposomal amphotericin B 50 mg injection for treatment of fungal infections in hospitals",
        "item_uom": "injections",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "1579200",
        "notice_id": "5IN026",
        "notice_url": "https://files.capt.gov.kw/media/62143405-06f1-4202-97ca-ec50d07f97ca.pdf",
        "query_text": "antifungal, injection, hospitals, ministry of health",
        "dedup_key": "capt-board-2025-40-5in026",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-05-11",
        "closing_date": "",
        "title": "Direct contract 5TB006 for rivaroxaban 10 mg tablets",
        "description": "CAPT board minutes meeting 2025/40 record Ministry of Health direct contract 5TB006 to purchase XARELTO rivaroxaban 10 mg tablets for blood-clot treatment in hospitals from Ali Abdulwahab Al Mutawa Commercial Company on behalf of Bayer Middle East FZE and Bayer AG.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "367800",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Ali Abdulwahab Al Mutawa Commercial Company / Bayer Middle East FZE / Bayer AG",
        "awarded_date": "2025-05-05",
        "awarded_value_detail": "367,800 KWD",
        "contract_period": "",
        "item_no": "43",
        "item_description": "XARELTO rivaroxaban 10 mg tablets for blood-clot treatment",
        "item_uom": "tablets",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "367800",
        "notice_id": "5TB006",
        "notice_url": "https://files.capt.gov.kw/media/62143405-06f1-4202-97ca-ec50d07f97ca.pdf",
        "query_text": "anticoagulant, rivaroxaban, tablets, ministry of health",
        "dedup_key": "capt-board-2025-40-5tb006",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-07-06",
        "closing_date": "",
        "title": "Direct contract 4LB493 for Dimension chemistry analyzer reagents and consumables",
        "description": "CAPT board minutes meeting 2025/55 record Ministry of Health direct contract 4LB493 to purchase 63 reagents and consumable items for Dimension chemistry analyzers for all laboratories from Al Sultan United Medical Company on behalf of Siemens Healthineers. CAPT approved all items except item 62 due to available stock.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "524331.733",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Al Sultan United Medical Company / Siemens Healthineers",
        "awarded_date": "2025-06-16",
        "awarded_value_detail": "524,331.733 KWD",
        "contract_period": "",
        "item_no": "3",
        "item_description": "63 reagents and consumable items for Dimension chemistry analyzers for all laboratories",
        "item_uom": "items",
        "item_quantity": "63",
        "item_unit_price": "",
        "item_awarded_value": "524331.733",
        "notice_id": "4LB493",
        "notice_url": "https://files.capt.gov.kw/media/cd36c257-13e1-4143-8911-c7bcb759b220.pdf",
        "query_text": "laboratory, chemistry analyzer, reagents, consumables, ministry of health",
        "dedup_key": "capt-board-2025-55-4lb493",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-07-06",
        "closing_date": "",
        "title": "First extension approval for Ministry of Health small works contract at Hassan Makki Juma Surgery Center",
        "description": "CAPT board minutes meeting 2025/55 record approval of the first extension for Ministry of Health tender S/M Kh A 2020/2019/30 covering small-scale maintenance, construction, and expansion works for Ministry of Health buildings and centers, group four at Hassan Makki Juma Surgery Center and related facilities, with Kamiran General Trading and Contracting.",
        "buyer": "Ministry of Health",
        "classification": "contract extension approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "0",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Kamiran General Trading and Contracting",
        "awarded_date": "2025-06-16",
        "awarded_value_detail": "Time extension only without financial consideration",
        "contract_period": "2025-10-25 to 2026-10-24",
        "item_no": "8",
        "item_description": "First extension of Ministry of Health small works contract for Hassan Makki Juma Surgery Center and related facilities",
        "item_uom": "contract",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "0",
        "notice_id": "smkh-2020-2019-30-ext1",
        "notice_url": "https://files.capt.gov.kw/media/cd36c257-13e1-4143-8911-c7bcb759b220.pdf",
        "query_text": "ministry of health, surgery center, maintenance, extension, healthcare",
        "dedup_key": "capt-board-2025-55-smkh-2020-2019-30-ext1",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-07-06",
        "closing_date": "",
        "title": "First extension approval for Ministry of Health small works contract in Mubarak Al-Kabeer health area",
        "description": "CAPT board minutes meeting 2025/55 record approval of the first extension for Ministry of Health tender S/M Kh A 2020/2019/30, contract 19, covering small-scale maintenance, construction, and expansion works for Ministry of Health buildings, hospitals, and centers in the Mubarak Al-Kabeer health area, with Kamiran General Trading and Contracting.",
        "buyer": "Ministry of Health",
        "classification": "contract extension approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "0",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Kamiran General Trading and Contracting",
        "awarded_date": "2025-06-16",
        "awarded_value_detail": "Time extension only without financial consideration",
        "contract_period": "2025-10-11 to 2026-10-10",
        "item_no": "9",
        "item_description": "First extension of Ministry of Health small works contract for the Mubarak Al-Kabeer health area",
        "item_uom": "contract",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "0",
        "notice_id": "smkh-2020-2019-19-ext1",
        "notice_url": "https://files.capt.gov.kw/media/cd36c257-13e1-4143-8911-c7bcb759b220.pdf",
        "query_text": "ministry of health, mubarak al-kabeer, maintenance, extension, healthcare",
        "dedup_key": "capt-board-2025-55-smkh-2020-2019-19-ext1",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-07-06",
        "closing_date": "",
        "title": "First extension approval for Ministry of Health small works contract group seven",
        "description": "CAPT board minutes meeting 2025/55 record approval of the first time extension for Ministry of Health tender S/M Kh A 2020/2019/30 covering small-scale maintenance, construction, and expansion works for Ministry of Health buildings, hospitals, and centers, group seven, with Mechanical Engineering and Contracting Company.",
        "buyer": "Ministry of Health",
        "classification": "contract extension approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "0",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Mechanical Engineering and Contracting Company",
        "awarded_date": "2025-06-16",
        "awarded_value_detail": "Time extension only without financial consideration",
        "contract_period": "2025-10-25 to 2026-10-24",
        "item_no": "10",
        "item_description": "First extension of Ministry of Health small works contract for group seven",
        "item_uom": "contract",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "0",
        "notice_id": "smkh-2020-2019-07-ext1",
        "notice_url": "https://files.capt.gov.kw/media/cd36c257-13e1-4143-8911-c7bcb759b220.pdf",
        "query_text": "ministry of health, maintenance, extension, healthcare, group seven",
        "dedup_key": "capt-board-2025-55-smkh-2020-2019-07-ext1",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-07-06",
        "closing_date": "",
        "title": "First extension approval for Ministry of Health small works contract group six",
        "description": "CAPT board minutes meeting 2025/55 record approval of the first extension for Ministry of Health tender S/M Kh A 2020/2019/30 covering small-scale maintenance, construction, and expansion works for Ministry of Health buildings, hospitals, and centers, group six, including the psychiatric, physical medicine, and Al Sariya hospitals and related facilities, with Mechanical Engineering and Contracting Company.",
        "buyer": "Ministry of Health",
        "classification": "contract extension approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "0",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Mechanical Engineering and Contracting Company",
        "awarded_date": "2025-06-16",
        "awarded_value_detail": "Time extension only without financial consideration",
        "contract_period": "2025-10-25 to 2026-10-24",
        "item_no": "11",
        "item_description": "First extension of Ministry of Health small works contract for group six including psychiatric and physical medicine hospital facilities",
        "item_uom": "contract",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "0",
        "notice_id": "smkh-2020-2019-06-ext1",
        "notice_url": "https://files.capt.gov.kw/media/cd36c257-13e1-4143-8911-c7bcb759b220.pdf",
        "query_text": "ministry of health, psychiatric hospital, physical medicine, maintenance, extension, healthcare",
        "dedup_key": "capt-board-2025-55-smkh-2020-2019-06-ext1",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-07-06",
        "closing_date": "",
        "title": "First extension approval for Ministry of Health small works contract in Ahmadi health area",
        "description": "CAPT board minutes meeting 2025/55 record approval of the first extension for Ministry of Health tender S/M Kh A 2020/2019/30 covering small-scale maintenance, construction, and expansion works for Ministry of Health buildings, hospitals, and centers, group ten in the Ahmadi health area, with Umm Al Qura International General Trading and Contracting.",
        "buyer": "Ministry of Health",
        "classification": "contract extension approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "0",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Umm Al Qura International General Trading and Contracting",
        "awarded_date": "2025-06-16",
        "awarded_value_detail": "Time extension only without financial consideration",
        "contract_period": "2025-10-16 to 2026-10-15",
        "item_no": "12",
        "item_description": "First extension of Ministry of Health small works contract for the Ahmadi health area",
        "item_uom": "contract",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "0",
        "notice_id": "smkh-2020-2019-10-ext1",
        "notice_url": "https://files.capt.gov.kw/media/cd36c257-13e1-4143-8911-c7bcb759b220.pdf",
        "query_text": "ministry of health, ahmadi, maintenance, extension, healthcare",
        "dedup_key": "capt-board-2025-55-smkh-2020-2019-10-ext1",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-07-06",
        "closing_date": "",
        "title": "First extension approval for Ministry of Health small works contract at Ibn Sina Hospital",
        "description": "CAPT board minutes meeting 2025/55 record approval of the first extension for Ministry of Health tender S/M Kh A 2020/2019/30 covering small-scale maintenance, construction, and expansion works for Ministry of Health buildings, hospitals, and centers, group three at Ibn Sina Hospital and related facilities, with Al Wajha Al Haditha General Trading and Contracting Establishment.",
        "buyer": "Ministry of Health",
        "classification": "contract extension approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "0",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Al Wajha Al Haditha General Trading and Contracting Establishment",
        "awarded_date": "2025-06-16",
        "awarded_value_detail": "Time extension only without financial consideration",
        "contract_period": "2025-10-25 to 2026-10-24",
        "item_no": "13",
        "item_description": "First extension of Ministry of Health small works contract for Ibn Sina Hospital and related facilities",
        "item_uom": "contract",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "0",
        "notice_id": "smkh-2020-2019-03-ext1",
        "notice_url": "https://files.capt.gov.kw/media/cd36c257-13e1-4143-8911-c7bcb759b220.pdf",
        "query_text": "ministry of health, ibn sina hospital, maintenance, extension, healthcare",
        "dedup_key": "capt-board-2025-55-smkh-2020-2019-03-ext1",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2025-05-11",
        "closing_date": "",
        "title": "Third extension approval for Ministry of Health land transport services contract",
        "description": "CAPT board minutes meeting 2025/40 record approval of the third extension and change order for Ministry of Health tender S/M Kh A 2018/2017/22 for leasing land transport buses with drivers for Ministry of Health services, with Yousif Al Owaid & Sons Automotive Company.",
        "buyer": "Ministry of Health",
        "classification": "contract extension approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "231012",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Yousif Al Owaid & Sons Automotive Company",
        "awarded_date": "2025-05-05",
        "awarded_value_detail": "231,012 KWD increase",
        "contract_period": "2025-04-30 to 2025-07-31",
        "item_no": "49",
        "item_description": "Third extension of land transport bus lease with drivers for Ministry of Health services",
        "item_uom": "contract",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "231012",
        "notice_id": "smkh-2018-2017-22-ext3",
        "notice_url": "https://files.capt.gov.kw/media/62143405-06f1-4202-97ca-ec50d07f97ca.pdf",
        "query_text": "ministry of health, transport, buses, extension, healthcare",
        "dedup_key": "capt-board-2025-40-smkh-2018-2017-22-ext3",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "Seventh extension approval for Ministry of Health facility security services in Sabah and Ahmadi health areas",
        "description": "CAPT board minutes meeting 2024/10 record approval of the seventh extension for Ministry of Health tender S/M Kh A 2017/2016/23 for security services at ministry facilities, group three in the Sabah and Ahmadi health areas, with Markaz Al Rowad Security Services branch of Al Rowad المتحدة.",
        "buyer": "Ministry of Health",
        "classification": "contract extension approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "335301.232",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Markaz Al Rowad Security Services / Al Rowad United General Trading and Contracting",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "335,301.232 KWD",
        "contract_period": "2024-06-18 to 2024-08-17",
        "item_no": "29",
        "item_description": "Seventh extension of security services contract for Ministry of Health facilities in Sabah and Ahmadi health areas",
        "item_uom": "contract",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "335301.232",
        "notice_id": "smkh-2017-2016-23-ext7",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "ministry of health, security, sabah, ahmadi, extension, healthcare",
        "dedup_key": "capt-board-2024-10-smkh-2017-2016-23-ext7",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "Six-month extension approval for Ministry of Health land transport bus services with National Passenger Transport",
        "description": "CAPT board minutes meeting 2024/10 record approval of a six-month extension and first change order for Ministry of Health tender S/M Kh A 2018/2017/22, item two, for land transport bus services with drivers, with National Passenger Transport Company.",
        "buyer": "Ministry of Health",
        "classification": "contract extension approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "35121.360",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "National Passenger Transport Company",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "35,121.360 KWD increase",
        "contract_period": "2024-04-24 to 2024-10-23",
        "item_no": "32",
        "item_description": "Six-month extension of land transport bus services contract with drivers for Ministry of Health services",
        "item_uom": "contract",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "35121.360",
        "notice_id": "smkh-2018-2017-22-national-ext1",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "ministry of health, transport, buses, extension, healthcare",
        "dedup_key": "capt-board-2024-10-smkh-2018-2017-22-national-ext1",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "Six-month extension approval for Ministry of Health land transport bus services with Mohammad Naser Al Hajri & Sons",
        "description": "CAPT board minutes meeting 2024/10 record approval of a six-month extension and second change order for Ministry of Health tender 2/2017/2018, items 1 and 4, for land transport bus services with drivers, with Mohammad Naser Al Hajri & Sons Automotive Company.",
        "buyer": "Ministry of Health",
        "classification": "contract extension approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "-93558.750",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Mohammad Naser Al Hajri & Sons Automotive Company",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "93,558.750 KWD reduction",
        "contract_period": "2024-04-30 to 2024-10-29",
        "item_no": "33",
        "item_description": "Six-month extension of land transport bus services contract with drivers for Ministry of Health services",
        "item_uom": "contract",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "-93558.750",
        "notice_id": "smkh-2018-2017-2-hajri-ext1",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "ministry of health, transport, buses, extension, healthcare",
        "dedup_key": "capt-board-2024-10-smkh-2018-2017-2-hajri-ext1",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "First change order approval for cardiac catheterization guidewire and diagnostic medical supplies",
        "description": "CAPT board minutes meeting 2024/10 record approval of the first change order increasing practice 039CA1 for guidewire and diagnostic medical supplies for the cardiac catheterization department at Al Dabbous Cardiac Surgery Center in Adan, under the contract with Central Circle Company on behalf of Abbott Vascular.",
        "buyer": "Ministry of Health",
        "classification": "change order approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "51050",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Central Circle Company / Abbott Vascular",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "51,050 KWD increase",
        "contract_period": "",
        "item_no": "36",
        "item_description": "Guidewire and diagnostic medical supplies for cardiac catheterization department at Al Dabbous Cardiac Surgery Center",
        "item_uom": "medical supplies",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "51050",
        "notice_id": "039CA1-change1",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "cardiac catheterization, guidewire, diagnostic, medical supplies, ministry of health",
        "dedup_key": "capt-board-2024-10-039ca1-change1",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "First change order approval for endoscopic cholecystectomy kits",
        "description": "CAPT board minutes meeting 2024/10 record approval of the first change order increasing practice 2SD055 for Bladeless KIT ENDO CHOLECYSTECTOMY medical kits for laparoscopic gallbladder removal for hospitals, with Al Taqadum Technology.",
        "buyer": "Ministry of Health",
        "classification": "change order approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "70580",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Al Taqadum Technology",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "70,580 KWD increase",
        "contract_period": "",
        "item_no": "37",
        "item_description": "Bladeless KIT ENDO CHOLECYSTECTOMY medical kits for laparoscopic gallbladder removal",
        "item_uom": "kits",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "70580",
        "notice_id": "2SD055-change1",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "endoscopic surgery, cholecystectomy, kits, medical supplies, ministry of health",
        "dedup_key": "capt-board-2024-10-2sd055-change1",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "First extension approval for blood bank system supply and installation contract",
        "description": "CAPT board minutes meeting 2024/10 record approval of the first extension for parts of Ministry of Health tender S/M Kh A 2019/2018/24 for supply and installation of automated systems at branch blood banks linked to the main center, with Al Taqadum Technology.",
        "buyer": "Ministry of Health",
        "classification": "contract extension approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "96659",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Al Taqadum Technology",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "96,659 KWD",
        "contract_period": "2023-11-27 to 2024-05-26",
        "item_no": "30",
        "item_description": "First extension for automated systems at branch blood banks linked to the main blood bank center",
        "item_uom": "contract",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "96659",
        "notice_id": "smkh-2019-2018-24-bloodbank-ext1",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "blood bank, automated system, extension, ministry of health, healthcare",
        "dedup_key": "capt-board-2024-10-smkh-2019-2018-24-bloodbank-ext1",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "First extension approval for popular incinerator operation and maintenance contract",
        "description": "CAPT board minutes meeting 2024/10 record approval of the first extension for Ministry of Health tender M Kh A 2020/2019/11 for operation, maintenance, and management of the popular incinerator, with National Cleaning Company.",
        "buyer": "Ministry of Health",
        "classification": "contract extension approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "36753.839",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "National Cleaning Company",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "36,753.839 KWD",
        "contract_period": "2024-03-01 to 2024-05-15",
        "item_no": "34",
        "item_description": "First extension of operation, maintenance, and management contract for the popular incinerator",
        "item_uom": "contract",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "36753.839",
        "notice_id": "mkh-2020-2019-11-incinerator-ext1",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "incinerator, maintenance, extension, ministry of health, healthcare waste",
        "dedup_key": "capt-board-2024-10-mkh-2020-2019-11-incinerator-ext1",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "First change order approval for hospital and health-center meal services group four",
        "description": "CAPT board minutes meeting 2024/10 record approval of the first change order increasing Ministry of Health tender M Kh A D10/2014 for preparation and provision of meals to hospitals and health centers, group four, with Jamal Commercial Company.",
        "buyer": "Ministry of Health",
        "classification": "change order approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "1836563.591",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Jamal Commercial Company",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "1,836,563.591 KWD increase",
        "contract_period": "",
        "item_no": "35",
        "item_description": "Preparation and provision of meals for hospitals and health centers, group four",
        "item_uom": "service contract",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "1836563.591",
        "notice_id": "mkhd10-2014-meals-change1",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "hospital meals, health centers, change order, ministry of health, healthcare",
        "dedup_key": "capt-board-2024-10-mkhd10-2014-meals-change1",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "First change order approval for ODEFSEY HIV treatment tablets",
        "description": "CAPT board minutes meeting 2024/10 record approval of the first change order increasing contract 22/C0635 for ODEFSEY HIV treatment tablets for patients at the Communicable Diseases Hospital, with Warba Medical Supplies.",
        "buyer": "Ministry of Health",
        "classification": "change order approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "195449.940",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Warba Medical Supplies",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "195,449.940 KWD increase",
        "contract_period": "",
        "item_no": "22",
        "item_description": "ODEFSEY HIV treatment tablets for patients at the Communicable Diseases Hospital",
        "item_uom": "tablets",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "195449.940",
        "notice_id": "22C0635-change1",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "hiv, communicable diseases hospital, tablets, change order, ministry of health",
        "dedup_key": "capt-board-2024-10-22c0635-change1",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "Contract amount adjustment approval for TRACLEER bosentan 62.5 mg tablets",
        "description": "CAPT board minutes meeting 2024/10 record approval to revise the first change order amount for contract 23/C0563 covering TRACLEER bosentan 62.5 mg tablets for pulmonary hypertension treatment in hospitals, with Cura Health.",
        "buyer": "Ministry of Health",
        "classification": "change order approval",
        "status": "awarded",
        "currency": "USD",
        "amount": "976074",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Cura Health",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "976,074 USD revised amount",
        "contract_period": "",
        "item_no": "23",
        "item_description": "TRACLEER bosentan 62.5 mg tablets for pulmonary hypertension treatment",
        "item_uom": "tablets",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "976074",
        "notice_id": "23C0563-change1-revised",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "pulmonary hypertension, bosentan, tablets, change order, ministry of health",
        "dedup_key": "capt-board-2024-10-23c0563-change1-revised",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "First change order reduction approval for SINGULAIR montelukast 10 mg tablets",
        "description": "CAPT board minutes meeting 2024/10 record approval of the first change order reducing contract 22C1870 for SINGULAIR montelukast 10 mg tablets used for heart and respiratory diseases across health centers and hospitals, with Ahfad Hamad Saleh Al Humaidhi Pharmaceutical Company on behalf of MSD.",
        "buyer": "Ministry of Health",
        "classification": "change order approval",
        "status": "awarded",
        "currency": "USD",
        "amount": "482130",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Ahfad Hamad Saleh Al Humaidhi Pharmaceutical Company / MSD",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "482,130 USD revised amount",
        "contract_period": "",
        "item_no": "24",
        "item_description": "SINGULAIR montelukast 10 mg tablets for heart and respiratory disease treatment",
        "item_uom": "tablets",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "482130",
        "notice_id": "22C1870-change1-revised",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "montelukast, respiratory, tablets, change order, ministry of health",
        "dedup_key": "capt-board-2024-10-22c1870-change1-revised",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "Contract amount adjustment approval for DOPTELET avatrombopag 20 mg tablets",
        "description": "CAPT board minutes meeting 2024/10 record approval to revise the first change order amount for contract 23/C0615 covering DOPTELET avatrombopag 20 mg tablets for thrombocytopenia treatment in hospitals, with Bader Sultan & Brothers on behalf of Sobi Middle East and Swedish Orphan Biovitrum.",
        "buyer": "Ministry of Health",
        "classification": "change order approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "103095",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Bader Sultan & Brothers / Sobi Middle East / Swedish Orphan Biovitrum",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "103,095 KWD revised amount",
        "contract_period": "",
        "item_no": "25",
        "item_description": "DOPTELET avatrombopag 20 mg tablets for thrombocytopenia treatment",
        "item_uom": "tablets",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "103095",
        "notice_id": "23C0615-change1-revised",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "avatrombopag, thrombocytopenia, tablets, change order, ministry of health",
        "dedup_key": "capt-board-2024-10-23c0615-change1-revised",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "Time extension approval for Kuwait Cancer Center project contract",
        "description": "CAPT board minutes meeting 2024/10 record approval of a no-cost time extension for Ministry of Health tender S/M Kh A 2012/2011/17 covering design, construction, medical تجهيز, furnishing, and operational maintenance for the Kuwait Cancer Center project, with Alghanim International General Trading and Contracting.",
        "buyer": "Ministry of Health",
        "classification": "contract extension approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "0",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Alghanim International General Trading and Contracting",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "Time extension only without financial consideration",
        "contract_period": "2024-04-23 to 2024-09-06",
        "item_no": "27",
        "item_description": "No-cost time extension for the Kuwait Cancer Center project contract",
        "item_uom": "contract",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "0",
        "notice_id": "smkh-2012-2011-17-cancer-center-ext",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "cancer center, project, extension, ministry of health, healthcare",
        "dedup_key": "capt-board-2024-10-smkh-2012-2011-17-cancer-center-ext",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "First extension approval for Ministry of Health electronic payment services contract",
        "description": "CAPT board minutes meeting 2024/10 record approval of the first extension for contract 333/2022/2021/33 covering electronic payment services for the Ministry of Health, with the Shared Automated Banking Services Company.",
        "buyer": "Ministry of Health",
        "classification": "contract extension approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "250000",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Shared Automated Banking Services Company",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "250,000 KWD",
        "contract_period": "2024-05-07 to 2024-08-06",
        "item_no": "21",
        "item_description": "First extension of the electronic payment services contract for the Ministry of Health",
        "item_uom": "contract",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "250000",
        "notice_id": "smkh-2022-2021-333-payment-ext1",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "electronic payment, services, ministry of health, extension, healthcare",
        "dedup_key": "capt-board-2024-10-smkh-2022-2021-333-payment-ext1",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "Second change order and six-month extension approval for Ministry of Health land transport bus services with Yousif Al Owaid & Sons",
        "description": "CAPT board minutes meeting 2024/10 record approval of a six-month extension and second change order for Ministry of Health tender S/M Kh A 2018/2017/2, items 1 and 4, for land transport bus services with drivers, with Yousif Al Owaid & Sons Automotive Company.",
        "buyer": "Ministry of Health",
        "classification": "contract extension approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "464042.250",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Yousif Al Owaid & Sons Automotive Company",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "464,042.250 KWD increase",
        "contract_period": "2024-04-30 to 2024-10-29",
        "item_no": "31",
        "item_description": "Six-month extension of land transport bus services contract with drivers for Ministry of Health services",
        "item_uom": "contract",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "464042.250",
        "notice_id": "smkh-2018-2017-2-owaid-ext2",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "ministry of health, transport, buses, extension, healthcare",
        "dedup_key": "capt-board-2024-10-smkh-2018-2017-2-owaid-ext2",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2026-01-25",
        "closing_date": "",
        "title": "Direct contract 033AK5 for STAY-SAFE CAPD 1.5% 2L peritoneal dialysis solution",
        "description": "CAPT board minutes meeting 2026/5 record Ministry of Health direct contract 033AK5 to purchase STAY-SAFE CAPD 1.5% 2L peritoneal dialysis solution for kidney dialysis centers from Mohammad Naser Al Hajri & Sons as local distributor for Fresenius Medical Care, with a total amount of 95,580 KWD.",
        "buyer": "Ministry of Health",
        "classification": "direct contract approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "95580",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Mohammad Naser Al Hajri & Sons / Fresenius Medical Care",
        "awarded_date": "2026-01-20",
        "awarded_value_detail": "95,580 KWD",
        "contract_period": "",
        "item_no": "22",
        "item_description": "STAY-SAFE CAPD 1.5% 2L peritoneal dialysis solution for kidney dialysis centers",
        "item_uom": "",
        "item_quantity": "",
        "item_unit_price": "",
        "item_awarded_value": "95580",
        "notice_id": "033AK5",
        "notice_url": "https://files.capt.gov.kw/media/649bebdf-2723-44f1-b4b4-bf82625db633.pdf",
        "query_text": "peritoneal dialysis, CAPD, stay-safe, fresenius, kidney dialysis centers, ministry of health",
        "dedup_key": "capt-board-2026-5-033ak5",
    },
    {
        "source": "CAPT Board Minutes",
        "country": "Kuwait",
        "country_code": "KW",
        "publication_date": "2024-06-30",
        "closing_date": "",
        "title": "Second extension approval for incinerator operation, maintenance, and management contract",
        "description": "CAPT board minutes meeting 2024/10 record approval of the second extension for Ministry of Health tender S/M Kh A 2018/2017/23 covering operation, maintenance, and management of the incinerator, with Metals and Transforming Industries Company.",
        "buyer": "Ministry of Health",
        "classification": "contract extension approval",
        "status": "awarded",
        "currency": "KWD",
        "amount": "25740",
        "awarding_agency_name": "Ministry of Health",
        "supplier_name": "Metals and Transforming Industries Company",
        "awarded_date": "2024-06-24",
        "awarded_value_detail": "25,740 KWD",
        "contract_period": "2024-03-01 to 2024-04-09",
        "item_no": "28",
        "item_description": "Second extension of operation, maintenance, and management contract for the incinerator",
        "item_uom": "contract",
        "item_quantity": "1",
        "item_unit_price": "",
        "item_awarded_value": "25740",
        "notice_id": "smkh-2018-2017-23-incinerator-ext2",
        "notice_url": "https://files.capt.gov.kw/media/e059d7ec-5af9-43f8-9d2a-6aff21a2ab4e.pdf",
        "query_text": "incinerator, maintenance, extension, ministry of health, healthcare waste",
        "dedup_key": "capt-board-2024-10-smkh-2018-2017-23-incinerator-ext2",
    },
]
